---
bibliography: references.bib
---

It is important to note that the main dataset used in this paper, the UK Household Longitudinal Study (UKHLS), is used in two distinct capacities: firstly to calibrate a model to produce a vector of conditional expected probabilities of individuals ending up in each of the mutually exclusive economic (in)activity states at the next discrete period; and secondly to construct a representative population sample frame used to produce the reference population. Using the algebraic terminology introduced in appendix B, we call the representative population sample frame $X^{Ref}$, which is then artificially modified through the overwriting of factors of interest, $Z$, to form the counterfactual population, $X^{Alt}$. The distinction between these two uses, and ways in which the UKHLS is used in these two capacities, will now be discussed.

The UKHLS is a household panel survey, which aims to follow up all individuals in households selected at random via the Postcode Address File (PAF) annually from the first 12 month period of its operation, 2009, for each subsequent 12 month period. Within the UKHLS, each 12 month period is referred to as a wave, and the first wave referred to as wave a. For our purposes, the data required for calibrating the model are those where individuals have been successfully recontacted between consecutive waves, and the economic (in)activity status at both waves $T$ and $T+1$ have been successfully recorded. The observations in our model therefore comprise $D ≡ \{y,X\}$, where $y= y_{t+1}$, the economic (in)activity status at wave $T+1$, and $X= \{W,y_t,Z\}$, i.e. sociodemographic confounders of interest $W$, economic (in)activity status at wave $T$, $y_t$, and the factor or factors of interest $Z$. (Implicitly, $W$ and $Z$ are also as recorded at wave $T$, and for an individual factors like age are of course liable to change over time.)

When calibrating the model, the observations used $D$ therefore comprise paired observations from individuals who have been successfully followed up between consecutive waves, with the model response term being from wave $T+1$ and other variables from wave $T$. This means both that the same individual may contribute multiple observations to the calibration dataset if paired consecutive observations of their economic (in)activity status over multiple waves has been successfully recorded. observations from a specific individual from a given wave $T$ will not be included in the calibration dataset if their corresponding economic (in)activity status at the following wave $y_{t+1}$ has not been successfully recorded; but also that the same individual may contribute multiple observations to the calibration dataset if paired consecutive observations of their economic (in)activity status over multiple waves has been successfully recorded. These observations comprising paired statuses between consecutive waves $\{y_{t+1},y_t\}$ are therefore assumed to be conditionally independent given $W$ and $Z$. This assumption was checked by comparing the AIC and BIC of alternative model specifications that included additional historical status terms - $\{y_{t+1},y_t,y_{t-1}\}$,$\{y_{t+1},y_t,y_{t-1},y_{t-2}\}$, and so on – which were not found to lead to improvements in penalized model fit.[^1] AIC and BIC was also used to select between a number of candidate model structures for including the effects of sociodemographic confounders, $W$ [@akaike1974; @schwarz1978]. This led to the identification of what we describe as our foundational model specification, which is detailed later. Our foundational model specification includes a specific treatment of $W$ and $y_t$. Model specifications including one or more factors of interest, $Z$, are referred to as extended models, which contain all terms in the foundational model specification plus the additional term or terms contained in $Z$; the foundational model specification can therefore be considered a restricted version of each extended model specification. Again, AIC and BIC, along with researcher judgement, is used to determine which extended model specification to use for simulation.

[^1]: This assessment of whether additional lagged terms on y should be included is conceptually similar to the selection of the number of autoregressive terms $p$ to use in an $AR(p)$ model specification [@hyndman2021].

Regarding the use of the UKHLS data for model prediction, the last complete pre-pandemic wave pairing, i.e. waves $i-j$, was used. The use of this wave-pairing represents a compromise between a range of completing considerations: on the one hand, sample attrition tends to increase over time, meaning that data from earlier waves are likely to be more completed. But on the other hand, earlier data are likely to be less representative of contemporary UK sociodemographic characteristics than later data. Finally, data covering the pandemic and earlier post pandemic period are likely to have compositions, especially of economic (in)activity states, unrepresentative of non-pandemic periods.

As described above, the procedure using data from waves i-j for model prediction involved identifying all complete observations from this wave for variables $\{W,y_t,Z\}$ and using them to construct the reference population sample frame $X^{Ref}$. Using the procedure described above, for the counterfactual sample frame $X^{Alt}$ the values of $Z$ were ‘switched off’, i.e. set to 0, in the case of a binary indicator, or standardised and normalized, then moved one standardised unit in the ‘good’ direction for continuous indicators. In the case of the continuous indicator presented in this paper there were a number of different ways of implementing the concept of moving $Z$ one standardised unit in the good direction, due to the factor of interest – health – being recorded separately for mental health and physical health, and an interaction term between these two health subdomains being identified as important for modelling these factors appropriately. 