<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jon Minton">
<meta name="author" content="Martin Taulbut">
<meta name="author" content="Neil Chalmers">
<meta name="author" content="Deborah Shipton">
<meta name="author" content="Andy Pulford">

<title>Simulating the impact of changes to health on economic status using multinomial logistic regression and the UK Household Longitudinal Study</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="main_files/libs/clipboard/clipboard.min.js"></script>
<script src="main_files/libs/quarto-html/quarto.js"></script>
<script src="main_files/libs/quarto-html/popper.min.js"></script>
<script src="main_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="main_files/libs/quarto-html/anchor.min.js"></script>
<link href="main_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="main_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="main_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="main_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="main_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#economic-activity-and-economic-inactivity-in-the-uk" id="toc-economic-activity-and-economic-inactivity-in-the-uk" class="nav-link" data-scroll-target="#economic-activity-and-economic-inactivity-in-the-uk"><span class="header-section-number">2.1</span> Economic activity and economic inactivity in the UK</a></li>
  <li><a href="#background-to-modelling-strategies-and-approaches" id="toc-background-to-modelling-strategies-and-approaches" class="nav-link" data-scroll-target="#background-to-modelling-strategies-and-approaches"><span class="header-section-number">2.2</span> Background to modelling strategies and approaches</a></li>
  </ul></li>
  <li><a href="#general-methodological-considerations" id="toc-general-methodological-considerations" class="nav-link" data-scroll-target="#general-methodological-considerations"><span class="header-section-number">3</span> General Methodological Considerations</a>
  <ul class="collapse">
  <li><a href="#description-of-the-modelling-challenges-and-how-we-address-them" id="toc-description-of-the-modelling-challenges-and-how-we-address-them" class="nav-link" data-scroll-target="#description-of-the-modelling-challenges-and-how-we-address-them"><span class="header-section-number">3.1</span> Description of the modelling challenges and how we address them</a></li>
  <li><a href="#modelling-for-simulation" id="toc-modelling-for-simulation" class="nav-link" data-scroll-target="#modelling-for-simulation"><span class="header-section-number">3.2</span> Modelling for simulation</a></li>
  <li><a href="#data-source-used-the-uk-household-longitudinal-study" id="toc-data-source-used-the-uk-household-longitudinal-study" class="nav-link" data-scroll-target="#data-source-used-the-uk-household-longitudinal-study"><span class="header-section-number">3.3</span> Data Source Used: The UK Household Longitudinal Study</a></li>
  <li><a href="#categories-of-economic-inactivity" id="toc-categories-of-economic-inactivity" class="nav-link" data-scroll-target="#categories-of-economic-inactivity"><span class="header-section-number">3.4</span> Categories of economic (in)activity</a></li>
  <li><a href="#dual-uses-of-the-dataset" id="toc-dual-uses-of-the-dataset" class="nav-link" data-scroll-target="#dual-uses-of-the-dataset"><span class="header-section-number">3.5</span> Dual uses of the dataset</a></li>
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification"><span class="header-section-number">3.6</span> Model Specification</a>
  <ul class="collapse">
  <li><a href="#foundational-model-specification" id="toc-foundational-model-specification" class="nav-link" data-scroll-target="#foundational-model-specification"><span class="header-section-number">3.6.1</span> Foundational Model Specification</a></li>
  <li><a href="#extended-model-specification-1-health-as-a-discrete-variable" id="toc-extended-model-specification-1-health-as-a-discrete-variable" class="nav-link" data-scroll-target="#extended-model-specification-1-health-as-a-discrete-variable"><span class="header-section-number">3.6.2</span> Extended Model Specification 1: Health as a Discrete Variable</a></li>
  <li><a href="#extended-model-specification-2-modelling-health-as-a-continuous-outcome-using-the-sf-12" id="toc-extended-model-specification-2-modelling-health-as-a-continuous-outcome-using-the-sf-12" class="nav-link" data-scroll-target="#extended-model-specification-2-modelling-health-as-a-continuous-outcome-using-the-sf-12"><span class="header-section-number">3.6.3</span> Extended Model Specification 2: Modelling health as a continuous outcome using the SF-12</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results-developing-the-foundational-model" id="toc-results-developing-the-foundational-model" class="nav-link" data-scroll-target="#results-developing-the-foundational-model"><span class="header-section-number">4</span> Results: Developing the Foundational Model</a></li>
  <li><a href="#results-developing-the-extended-models" id="toc-results-developing-the-extended-models" class="nav-link" data-scroll-target="#results-developing-the-extended-models"><span class="header-section-number">5</span> Results: Developing the extended models</a>
  <ul class="collapse">
  <li><a href="#modelling-health-as-a-discrete-variable" id="toc-modelling-health-as-a-discrete-variable" class="nav-link" data-scroll-target="#modelling-health-as-a-discrete-variable"><span class="header-section-number">5.1</span> Modelling Health as a Discrete Variable</a>
  <ul class="collapse">
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection"><span class="header-section-number">5.1.1</span> Model selection</a></li>
  <li><a href="#model-predictions-and-simulations" id="toc-model-predictions-and-simulations" class="nav-link" data-scroll-target="#model-predictions-and-simulations"><span class="header-section-number">5.1.2</span> Model predictions and simulations</a></li>
  </ul></li>
  <li><a href="#modelling-health-as-continuous-variables" id="toc-modelling-health-as-continuous-variables" class="nav-link" data-scroll-target="#modelling-health-as-continuous-variables"><span class="header-section-number">5.2</span> Modelling Health as Continuous Variables</a>
  <ul class="collapse">
  <li><a href="#model-selection-1" id="toc-model-selection-1" class="nav-link" data-scroll-target="#model-selection-1"><span class="header-section-number">5.2.1</span> Model selection</a></li>
  <li><a href="#model-predictions-and-simulations-1" id="toc-model-predictions-and-simulations-1" class="nav-link" data-scroll-target="#model-predictions-and-simulations-1"><span class="header-section-number">5.2.2</span> Model predictions and simulations</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-key-findings" id="toc-summary-of-key-findings" class="nav-link" data-scroll-target="#summary-of-key-findings"><span class="header-section-number">6.1</span> Summary of Key Findings</a></li>
  <li><a href="#interpretation-of-findings" id="toc-interpretation-of-findings" class="nav-link" data-scroll-target="#interpretation-of-findings"><span class="header-section-number">6.2</span> Interpretation of Findings</a></li>
  <li><a href="#comparison-with-previous-research" id="toc-comparison-with-previous-research" class="nav-link" data-scroll-target="#comparison-with-previous-research"><span class="header-section-number">6.3</span> Comparison with Previous Research</a></li>
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications"><span class="header-section-number">6.4</span> Implications</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">6.5</span> Limitations</a></li>
  <li><a href="#future-research-directions" id="toc-future-research-directions" class="nav-link" data-scroll-target="#future-research-directions"><span class="header-section-number">6.6</span> Future Research Directions</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.7</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  <li><a href="#appendices" id="toc-appendices" class="nav-link" data-scroll-target="#appendices"><span class="header-section-number">8</span> Appendices</a>
  <ul class="collapse">
  <li><a href="#appendix-a-further-discussion-of-conditions-the-model-needs-to-satisfy" id="toc-appendix-a-further-discussion-of-conditions-the-model-needs-to-satisfy" class="nav-link" data-scroll-target="#appendix-a-further-discussion-of-conditions-the-model-needs-to-satisfy"><span class="header-section-number">8.1</span> Appendix A: Further discussion of conditions the model needs to satisfy</a></li>
  <li><a href="#appendix-b-further-discussion-of-generalised-linear-modelling-and-model-simulation-considerations" id="toc-appendix-b-further-discussion-of-generalised-linear-modelling-and-model-simulation-considerations" class="nav-link" data-scroll-target="#appendix-b-further-discussion-of-generalised-linear-modelling-and-model-simulation-considerations"><span class="header-section-number">8.2</span> Appendix B: Further discussion of generalised linear modelling and model simulation considerations</a>
  <ul class="collapse">
  <li><a href="#overview-of-what-models-contain" id="toc-overview-of-what-models-contain" class="nav-link" data-scroll-target="#overview-of-what-models-contain"><span class="header-section-number">8.2.1</span> Overview of what models contain</a></li>
  <li><a href="#selecting-between-model-specifications" id="toc-selecting-between-model-specifications" class="nav-link" data-scroll-target="#selecting-between-model-specifications"><span class="header-section-number">8.2.2</span> Selecting between model specifications</a></li>
  <li><a href="#simulation-to-quantify-the-effects-of-specific-factors" id="toc-simulation-to-quantify-the-effects-of-specific-factors" class="nav-link" data-scroll-target="#simulation-to-quantify-the-effects-of-specific-factors"><span class="header-section-number">8.2.3</span> Simulation to quantify the effects of specific factors</a></li>
  <li><a href="#moving-from-individual-level-to-population-level-estimates" id="toc-moving-from-individual-level-to-population-level-estimates" class="nav-link" data-scroll-target="#moving-from-individual-level-to-population-level-estimates"><span class="header-section-number">8.2.4</span> Moving from individual level to population level estimates</a></li>
  <li><a href="#using-the-approach-to-estimate-pafs-and-safs" id="toc-using-the-approach-to-estimate-pafs-and-safs" class="nav-link" data-scroll-target="#using-the-approach-to-estimate-pafs-and-safs"><span class="header-section-number">8.2.5</span> Using the approach to estimate PAFs and SAFs</a></li>
  </ul></li>
  <li><a href="#including-continuous-variables-in-the-model" id="toc-including-continuous-variables-in-the-model" class="nav-link" data-scroll-target="#including-continuous-variables-in-the-model"><span class="header-section-number">8.3</span> Including continuous variables in the model</a></li>
  <li><a href="#appendix-c-illustrative-individual-level-vignettes" id="toc-appendix-c-illustrative-individual-level-vignettes" class="nav-link" data-scroll-target="#appendix-c-illustrative-individual-level-vignettes"><span class="header-section-number">8.4</span> Appendix C: Illustrative individual level vignettes</a></li>
  <li><a href="#appendix-d-out-of-sample-predictive-scores-for-different-foundational-model-specifications" id="toc-appendix-d-out-of-sample-predictive-scores-for-different-foundational-model-specifications" class="nav-link" data-scroll-target="#appendix-d-out-of-sample-predictive-scores-for-different-foundational-model-specifications"><span class="header-section-number">8.5</span> Appendix D: Out-of-sample predictive scores for different foundational model specifications</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="main.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="main.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simulating the impact of changes to health on economic status using multinomial logistic regression and the UK Household Longitudinal Study</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Jon Minton </p>
             <p>Martin Taulbut </p>
             <p>Neil Chalmers </p>
             <p>Deborah Shipton </p>
             <p>Andy Pulford </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>Economic status is an important determinant of health, with unemployment and many forms of economic inactivity associated with worse morbidity and higher mortality. Health can also influence economic status, especially movement from employment to long-term sickness and from long-term sickness to employment. This paper uses modelling to estimate how improvements to health alter the composition of economic status at a population level in the UK, and show how model based population attributable fractions (PAFs) and sequential attributable fractions (SAFs) can be calculated using this approach.</p>
<p>Multinominal logistic regression was used to build a foundational model to estimate the economic status of a population in the next time period, based on age, sex and current economic status. This model was extended to include health as a predictor. The model was then applied to wave i of the UKHLS. We compared the baseline predictions with a counterfactual where the health measures were improved, using two approaches: we first modelled health as a discrete variable, in which limiting long term illness was ‘switched off’ in a counterfactual scenario to estimate its effects on transitions between states. And we secondly modelled health as a pair of linked continuous health variables - mental health and physical health - in which in the counterfactual scenarios standardised health scores were ‘improved’ by one standardised unit.</p>
<p>Although this paper is primarily methodological, the discrete health approach estimated that limiting long-term illness may be responsible for around 60% of economic inactivity due to long-term sickness; and that improving health more generally could reduce economic inactivity due to long-term sickness by around 30%. It appears improvements in physical health tend to reduce the size of long-term sickness related economic inactivity slightly more than equivalent improvements in mental health.</p>
<p>Further analysis will build on this methodology to quantify the impact of changes in structural, household and individual level factors on population-level economic status.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>There have been important and in some cases troubling trends in working age economic inactivity in the UK, especially in trends towards rising economic inactivity related to ill health.</p>
<p>This paper describes the development and results of a modelling framework that estimates the contribution of health to population-level economic activity and inactivity, controlling for demography and current economic status. The framework is highly adaptable and could be extended to include wider determinants of economic status in addition to health.</p>
<section id="economic-activity-and-economic-inactivity-in-the-uk" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="economic-activity-and-economic-inactivity-in-the-uk"><span class="header-section-number">2.1</span> Economic activity and economic inactivity in the UK</h2>
<p>Working-age adults in the UK can be divided by their main economic status into the employed, unemployed and the economically inactive. Employed people include employees and the self-employed who do at least one paid hour of work a week plus those temporarily away from work because they are on holiday or sick. Unemployed people are defined as those out of work and are either actively seeking work and are available to start work within the next two weeks or who are out of work, have found work and are about to start employment within the next two weeks. Economically inactive people are those out of work who are not available for or actively seeking employment. The main reasons for working-age economic inactivity in the UK include being in full-time education, long-term illness or disability, looking after home and family and (early)retired <span class="citation" data-cites="labourm2020">(<a href="#ref-labourm2020" role="doc-biblioref"><span>“Labour Market Overview, UK: October 2020”</span> 2020</a>)</span>.</p>
<p>Economic status is an important determinant of public health. Working is associated with better mental and physical health, while people who are long-term sick have the worst morbidity <span class="citation" data-cites="wilson2015 brown2012">(<a href="#ref-wilson2015" role="doc-biblioref">Wilson, Wilson, and Usher 2015</a>; <a href="#ref-brown2012" role="doc-biblioref">Brown et al. 2012</a>)</span> Unemployed adults and those looking after home and family have intermediate levels of health. Compared to the employed, working-age adults who become or remain unemployed or economically inactive (especially long-term sick or early retired) have an increased risk of mortality <span class="citation" data-cites="roelfs2011 åhs2006 kim2015">(<a href="#ref-roelfs2011" role="doc-biblioref">Roelfs et al. 2011</a>; <a href="#ref-åhs2006" role="doc-biblioref">Åhs and Westerling 2006</a>; <a href="#ref-kim2015" role="doc-biblioref">Kim et al. 2015</a>)</span>. For economically inactive students, the picture is more complex. Their mental health is poorer than those in employment; however, some evidence suggests this difference may be transitory, with the effect wearing off once they leave full-time education <span class="citation" data-cites="mccloud2023">(<a href="#ref-mccloud2023" role="doc-biblioref">McCloud et al. 2023</a>)</span>.</p>
<p>Health is also an important driver of economic status. In the UK, adults of all ages were more likely to be economically inactive if they had self-reported bad/very bad health than if they had self-reported good/very good health<span class="citation" data-cites="dey-chowdhury2022">(<a href="#ref-dey-chowdhury2022" role="doc-biblioref">Dey-Chowdhury and Thorne 2022</a>)</span>. Economic inactivity due to long-term sickness has also increased since 2019. While an ageing population and increased waiting lists for NHS treatment may have played a role in this, the UK’s worsening health record was also a major contributory factor <span class="citation" data-cites="tinson2022 howdoes2023">(<a href="#ref-tinson2022" role="doc-biblioref">Tinson, Major, and Finch 2022</a>; <a href="#ref-howdoes2023" role="doc-biblioref"><span>“How Does Economic Inactivity Compare Across Advanced Economies?”</span> 2023</a>)</span>.</p>
<p>Since the 1970s in Britain, inactivity has fallen for working-age women and risen for working-age men. Within this, the numbers inactive due to looking after home and family have decreased, while those inactive because of full-time education or long-term sickness has increased <span class="citation" data-cites="machin2023 dar2015">(<a href="#ref-machin2023" role="doc-biblioref">Machin and Wadsworth 2023</a>; <a href="#ref-dar2015" role="doc-biblioref">Dar 2015</a>)</span>. Alongside this, employment rates for mothers increased steadily in the 1980s and 1990s, while employment rates for people with disabilities declined until the early 1980s and did not recover in the next two decades <span class="citation" data-cites="berthoud2007">(<a href="#ref-berthoud2007" role="doc-biblioref">Berthoud 2007</a>)</span>. Between 2000 and 2018, economic inactivity for adults aged 16-64 fell only slightly, driven by increased labour market participation for women aged 50-64 <span class="citation" data-cites="herz">(<a href="#ref-herz" role="doc-biblioref">Herz and Rens, n.d.</a>)</span>.</p>
<p>Of particular concern to policy makers is the number of working-age adults whose economic inactivity is due to long-term sickness. 2.8 million adults in the UK were in this position in January-March 2024 <span class="citation" data-cites="labourm">(<a href="#ref-labourm" role="doc-biblioref"><span>“Labour Market Overview, UK: August 2024,”</span> n.d.</a>)</span>. This reflects both long-term and short-term trends. The long-term trend is a reflection of growing numbers of working-age adults on incapacity benefits (IB) since the 1970s. Both sexes were affected. Male levels increased sharply until mid-1990s before levelling off. Female levels continued to increase after mid-1990s but also levelled off in early 2000s <span class="citation" data-cites="anyadike-danes2008">(<a href="#ref-anyadike-danes2008" role="doc-biblioref">Anyadike-Danes and McVicar 2008</a>)</span>. These changes are likely to be due to a combination of factors: local and regional spatial differences in labour market demand and lower employment prospects linked to poor health and low skills <span class="citation" data-cites="beatty2013 roberts2022 plotnikova2020 machin2023">(<a href="#ref-beatty2013" role="doc-biblioref">Beatty and Fothergill 2013</a>; <a href="#ref-roberts2022" role="doc-biblioref">Roberts and Taylor 2022</a>; <a href="#ref-plotnikova2020" role="doc-biblioref">Plotnikova 2020</a>; <a href="#ref-machin2023" role="doc-biblioref">Machin and Wadsworth 2023</a>)</span>. There is some evidence that economic inactivity due to long-term sickness declined in the UK between the early 2000s and early to mid-2010s. Trends in long-term sickness stopped falling around the middle to latter half of the decade and have subsequently increased <span class="citation" data-cites="machin2023">(<a href="#ref-machin2023" role="doc-biblioref">Machin and Wadsworth 2023</a>)</span>. Quantifying the contribution of these factors to the growth in long-term sickness could help understand what to focus on, to reverse recent increases and prevent further growth.</p>
</section>
<section id="background-to-modelling-strategies-and-approaches" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="background-to-modelling-strategies-and-approaches"><span class="header-section-number">2.2</span> Background to modelling strategies and approaches</h2>
<p>In this paper, we use multinominal logistic regression to predict the distribution of the working-age population by economic status in the next time period. After creating a foundational model, which includes age, sex and current economic status, we consider two extended model specifications, both of which include at least one health-related variables in addition to the variables in the foundational model.</p>
<p>The first of these extended model specifications uses a binary variable, which is coded as <code>1</code> if the respondent reports having a limiting long-term illness, and <code>0</code> if they do not. The second extended model specification uses a continuous measure of health, derived from the physical health and mental health components of the Short Form (SF) 12 (SF-12) questionnaire <span class="citation" data-cites="ware1996">(<a href="#ref-ware1996" role="doc-biblioref">Ware, Kosinski, and Keller 1996</a>)</span>. We focus here on the pre-pandemic period 2010 to 2019, because the drivers of economic inactivity during the pandemic are likely to be different from those in the pre-COVID years.</p>
</section>
</section>
<section id="general-methodological-considerations" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> General Methodological Considerations</h1>
<p>This section of the paper will approach how we thought about problems, challenges and solutions of building a model that can answer questions on the contributions of specific factors on the levels of economic inactivity and activity in a population. We first describe what the model needs to accomplish; then describe modelling and simulation principles in general; lastly we move towards operationalisation and the specific model structure and content that we use in this manuscript.</p>
<section id="description-of-the-modelling-challenges-and-how-we-address-them" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="description-of-the-modelling-challenges-and-how-we-address-them"><span class="header-section-number">3.1</span> Description of the modelling challenges and how we address them</h2>
<p>The modelling strategy starts with the need to operationalise key assumptions about the economic (in)activity status of individuals over time, factors that may influence an individual’s economic (in)activity status, and the longitudinal study design of the UKHLS. We assume:</p>
<ol type="1">
<li>An individual can be in one of seven mutually exclusive and exhaustive economic (in)activity states at a given time period <span class="math inline">\(T\)</span>. Therefore we use a multinomial logistic regression.</li>
<li>A key factor expected to influence the economic (in)activity state of an individual at time <span class="math inline">\(T+1\)</span> is their economic (in)activity state in the previous time period <span class="math inline">\(T\)</span>.</li>
<li>A person’s age is expected to influence the probability of an individual being in each and every economic (in)activity state, and these effects are likely to be nonlinear. We explored whether age should be included using a polynomial or spline function within the model.</li>
<li>A person’s sex is also expected to be influential as to their probability of being in and moving to each economic (in)activity state. We explored whether sex should be included an independent or interactive variable within the model.</li>
<li>Once the modelling framework is sufficient in capturing those qualities represented by conditions (1-4), it should be readily extensible to capture the additional influence that other factors may have on the predicted probabilities of being in each mutually exclusive economic (in)activity state at time <span class="math inline">\(T\)</span>. Condition (1) indicates that a multivariate model should be used. By this we mean that the response variable Y comprises a vector of response outcomes, rather than a single response outcome. Knowing additionally from this condition that the states an individual can be in are mutually exclusive and exhaustive leads us to a choice of multinomial logistic regression as our main model framework. Multinomial logistic regression is an extension of standard logistic regression from two mutually exclusive states to K mutually exclusive states, where <span class="math inline">\(K\)</span> is an integer value, which in our case is seven: the number of mutually exclusive and exhaustive economic (in)activity states an individual can be in at a time period <span class="math inline">\(T\)</span>.</li>
</ol>
<p>Appendix A discusses the rationale for these conditions in more detail.</p>
<p>Within this paper, we refer to:</p>
<ul>
<li>The <strong>Foundational Model</strong>, which includes current economic status, age and sex.</li>
<li><strong>Extended Models</strong>, which add one or more predictor variables to the Foundational Model.</li>
</ul>
<p>By comparing scenarios in an extended model, where the additional variable or variables of interested are changed between scenarios, but the foundational model variables are kepy constant, we are able to produce estimates of the contribution of these variables of interest to population-level economic status.</p>
</section>
<section id="modelling-for-simulation" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="modelling-for-simulation"><span class="header-section-number">3.2</span> Modelling for simulation</h2>
<p>Appendix B contains a background to generalised linear models, how they are used for statistical simulation, and the specific type of model specification and processes and analyses conducted. This includes discussion of how the results from statistical simulation can be presented as PAFs and SAFs.</p>
</section>
<section id="data-source-used-the-uk-household-longitudinal-study" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-source-used-the-uk-household-longitudinal-study"><span class="header-section-number">3.3</span> Data Source Used: The UK Household Longitudinal Study</h2>
<p>Our first step was to build a foundational model to predict the future distribution of economic status in the population based on the current characteristics of that population. We do this using individuals’ observed economic states reported across ten waves of the UK Household Longitudinal Study (UKHLS), 2009-10 to 2018-19. Also known as Understanding Society, the UKHLS is a longitudinal household panel survey that aims to follow all individuals in households selected at random in the first wave, 2009. Even where households move, or individuals in initially selected household form new households, the UKHLS aims to interview them each subsequent year, along with any new household members.</p>
<p>Important strengths of the UKHLS for our purposes are its longitudinal nature and the richness of the data it collects. Because of its longitudinal nature, the UKHLS is ideal for tracking changes in individuals’ economic (in)activity states over time and seeing how a variety of factors at wave <span class="math inline">\(T\)</span> influence the subsequent state at time <span class="math inline">\(T+1\)</span>. Its collection of data on income, employment and other labour market outcomes, education, family and health is comprehensive compared to other large-scale surveys <span class="citation" data-cites="benzeval2023">(<a href="#ref-benzeval2023" role="doc-biblioref">Benzeval, Crossley, and Aguirre 2023</a>)</span>. Other advantages of UKHLS include its large sample size compared to other longitudinal surveys, its coverage of all age groups (rather than a specific birth cohort), and its potential for linkage with ecological data and individual-level administrative data. A key limitation is attrition (people dropping-out of the survey) and loss of representativeness over time <span class="citation" data-cites="platt2021">(<a href="#ref-platt2021" role="doc-biblioref">Platt et al. 2021</a>)</span>.</p>
<p>We use all the observations from waves i (2009-10) to waves j (2018-19) for which flows from T to T+1 are available. This means that any one individual can contribute multiple observations to the model, similar to autoregressive time-series models, so the model is based on unique observations, not unique individuals. We excluded waves k (2019-20) to m (2021-22), because changes in economic status are likely to have been affected by the COVID-19 epidemic during these years.</p>
</section>
<section id="categories-of-economic-inactivity" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="categories-of-economic-inactivity"><span class="header-section-number">3.4</span> Categories of economic (in)activity</h2>
<p>The UKHLS offers a number of levels of aggregation and disaggregation at which an individual’s economic (in)activity state can be divided. This ranges from two mutually exclusive states, {economically inactive, economically active}, through to a much larger number of economically inactive states. In the case of two mutually exclusive states, economically inactive includes full time students, those inactive for reasons of ill health, and full time carers, even though we may consider these to be qualitatively different categories and experiences. Similarly economically active includes both those who are presently employed, and those who are unemployed but seeking employment: again, qualitatively different categories. In order to be mindful of the hidden heterogeneity involved in the broader categories of economically inactive and economically active, we made use consistently of a seven-level grouping of economic (in)activity types from the UKHLS:</p>
<ul>
<li>Economically Active:
<ul>
<li>Employed</li>
<li>Unemployed</li>
</ul></li>
<li>Economically Inactive:
<ul>
<li>Long Term Sick</li>
<li>Full Time Student</li>
<li>Full Time Carer</li>
<li>Early Retired</li>
<li>Other</li>
</ul></li>
</ul>
<p>Using the terminology introduced in appendix B, our multinomial logistic regression model therefore has K=7 (and so J=6). Each of the seven states is treated as categorical, and model does not ‘know’ (in the sense there are no structural constraints) that, say, Long term Sick and Full Time Student are both types of Economic Inactivity, and that Employed and Unemployed are both types of Economic Activity.</p>
</section>
<section id="dual-uses-of-the-dataset" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="dual-uses-of-the-dataset"><span class="header-section-number">3.5</span> Dual uses of the dataset</h2>
<p>It is important to note that the main dataset used in this paper, the UK Household Longitudinal Study (UKHLS), is used in two distinct capacities: firstly to calibrate a model to produce a vector of conditional expected probabilities of individuals ending up in each of the mutually exclusive economic (in)activity states at the next discrete period; and secondly to construct a representative population sample frame used to produce the reference population. Using the algebraic terminology introduced in appendix B, we call the representative population sample frame <span class="math inline">\(X^{Ref}\)</span>, which is then artificially modified through the overwriting of factors of interest, <span class="math inline">\(Z\)</span>, to form the counterfactual population, <span class="math inline">\(X^{Alt}\)</span>. The distinction between these two uses, and ways in which the UKHLS is used in these two capacities, will now be discussed.</p>
<p>The UKHLS is a household panel survey, which aims to follow up all individuals in households selected at random via the Postcode Address File (PAF) annually from the first 12 month period of its operation, 2009, for each subsequent 12 month period. Within the UKHLS, each 12 month period is referred to as a wave, and the first wave referred to as wave a. For our purposes, the data required for calibrating the model are those where individuals have been successfully recontacted between consecutive waves, and the economic (in)activity status at both waves <span class="math inline">\(T\)</span> and <span class="math inline">\(T+1\)</span> have been successfully recorded. The observations in our model therefore comprise <span class="math inline">\(D ≡ \{y,X\}\)</span>, where <span class="math inline">\(y= y_{t+1}\)</span>, the economic (in)activity status at wave <span class="math inline">\(T+1\)</span>, and <span class="math inline">\(X= \{W,y_t,Z\}\)</span>, i.e.&nbsp;sociodemographic confounders of interest <span class="math inline">\(W\)</span>, economic (in)activity status at wave <span class="math inline">\(T\)</span>, <span class="math inline">\(y_t\)</span>, and the factor or factors of interest <span class="math inline">\(Z\)</span>. (Implicitly, <span class="math inline">\(W\)</span> and <span class="math inline">\(Z\)</span> are also as recorded at wave <span class="math inline">\(T\)</span>, and for an individual factors like age are of course liable to change over time.)</p>
<p>When calibrating the model, the observations used <span class="math inline">\(D\)</span> therefore comprise paired observations from individuals who have been successfully followed up between consecutive waves, with the model response term being from wave <span class="math inline">\(T+1\)</span> and other variables from wave <span class="math inline">\(T\)</span>. This means both that the same individual may contribute multiple observations to the calibration dataset if paired consecutive observations of their economic (in)activity status over multiple waves has been successfully recorded. observations from a specific individual from a given wave <span class="math inline">\(T\)</span> will not be included in the calibration dataset if their corresponding economic (in)activity status at the following wave <span class="math inline">\(y_{t+1}\)</span> has not been successfully recorded; but also that the same individual may contribute multiple observations to the calibration dataset if paired consecutive observations of their economic (in)activity status over multiple waves has been successfully recorded. These observations comprising paired statuses between consecutive waves <span class="math inline">\(\{y_{t+1},y_t\}\)</span> are therefore assumed to be conditionally independent given <span class="math inline">\(W\)</span> and <span class="math inline">\(Z\)</span>. This assumption was checked by comparing the AIC and BIC of alternative model specifications that included additional historical status terms - <span class="math inline">\(\{y_{t+1},y_t,y_{t-1}\}\)</span>,<span class="math inline">\(\{y_{t+1},y_t,y_{t-1},y_{t-2}\}\)</span>, and so on – which were not found to lead to improvements in penalized model fit.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> AIC and BIC was also used to select between a number of candidate model structures for including the effects of sociodemographic confounders, <span class="math inline">\(W\)</span> <span class="citation" data-cites="akaike1974 schwarz1978">(<a href="#ref-akaike1974" role="doc-biblioref">Akaike 1974</a>; <a href="#ref-schwarz1978" role="doc-biblioref">Schwarz 1978</a>)</span>. This led to the identification of what we describe as our foundational model specification, which is detailed later. Our foundational model specification includes a specific treatment of <span class="math inline">\(W\)</span> and <span class="math inline">\(y_t\)</span>. Model specifications including one or more factors of interest, <span class="math inline">\(Z\)</span>, are referred to as extended models, which contain all terms in the foundational model specification plus the additional term or terms contained in <span class="math inline">\(Z\)</span>; the foundational model specification can therefore be considered a restricted version of each extended model specification. Again, AIC and BIC, along with researcher judgement, is used to determine which extended model specification to use for simulation.</p>
<p>Regarding the use of the UKHLS data for model prediction, the last complete pre-pandemic wave pairing, i.e.&nbsp;waves <span class="math inline">\(i-j\)</span>, was used. The use of this wave-pairing represents a compromise between a range of completing considerations: on the one hand, sample attrition tends to increase over time, meaning that data from earlier waves are likely to be more completed. But on the other hand, earlier data are likely to be less representative of contemporary UK sociodemographic characteristics than later data. Finally, data covering the pandemic and earlier post pandemic period are likely to have compositions, especially of economic (in)activity states, unrepresentative of non-pandemic periods.</p>
<p>As described above, the procedure using data from waves i-j for model prediction involved identifying all complete observations from this wave for variables <span class="math inline">\(\{W,y_t,Z\}\)</span> and using them to construct the reference population sample frame <span class="math inline">\(X^{Ref}\)</span>. Using the procedure described above, for the counterfactual sample frame <span class="math inline">\(X^{Alt}\)</span> the values of <span class="math inline">\(Z\)</span> were ‘switched off’, i.e.&nbsp;set to 0, in the case of a binary indicator, or standardised and normalized, then moved one standardised unit in the ‘good’ direction for continuous indicators. In the case of the continuous indicator presented in this paper there were a number of different ways of implementing the concept of moving <span class="math inline">\(Z\)</span> one standardised unit in the good direction, due to the factor of interest – health – being recorded separately for mental health and physical health, and an interaction term between these two health subdomains being identified as important for modelling these factors appropriately.</p>
</section>
<section id="model-specification" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="model-specification"><span class="header-section-number">3.6</span> Model Specification</h2>
<section id="foundational-model-specification" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="foundational-model-specification"><span class="header-section-number">3.6.1</span> Foundational Model Specification</h3>
<p>In appendix B, we state that our model specification must produce predictions of the economic (in)activity status for an individual at time <span class="math inline">\(T+1\)</span>, meaning our response is <span class="math inline">\(y= y_{t+1}\)</span>, given a predictor matrix <span class="math inline">\(X= \{W,y_t,Z\}\)</span>, where <span class="math inline">\(W\)</span> are sociodemographic confounders, <span class="math inline">\(y_t\)</span> is the economic (in)activity status at wave <span class="math inline">\(T\)</span>, and <span class="math inline">\(Z\)</span> represents the factor or factors of interest. This general specification still offers many researcher degrees of freedom in terms of how it may be implemented. Our approach was to first select what we call a common foundational model specification, in which <span class="math inline">\(X= \{W,y_t \}\)</span>, then use this foundational model specification as the starting point for one or more extended model specifications in which <span class="math inline">\(X= \{W,y_t,Z\}\)</span>. We considered it vital that <span class="math inline">\(W\)</span> includes at a minimum adequate controls for sex and age. We also explored the possibility that interactions between components of <span class="math inline">\(W\)</span> and <span class="math inline">\(y_t\)</span> may also be required.</p>
<p>Our final foundational model specification for the predictors <span class="math inline">\(X\)</span> was, using R’s formula interface:</p>
<blockquote class="blockquote">
<p><code>next_status ~ this_status * sex + splines::bs(age, knots=2, degree=3)</code></p>
</blockquote>
<p>Or equivalently:</p>
<blockquote class="blockquote">
<p><code>next_status ~ this_status * sex + splines::bs(age, df = 5)</code></p>
</blockquote>
<p>This final foundatonal model specification was selected after comparing eight possible foundational model specifications that incorporated event history (<code>this_status</code>), sex, and non-linear age effects: four specifications that included an interaction term between event history and sex (i.e.&nbsp;representing the concept that conditional transitions between states are influenced by sex), and four that did not. Within each of these groups of four, the number of degrees of freedom (the <code>df</code> parameter) in the <code>bs()</code> function was changed between 3 and 6. Further details, including results of performing repeated out-of-sample predictive fit estimation on four candidate models, are presented in Appendix D.</p>
<p>Both extended model specifications discussed in this manuscript begin with this foundational model specification, then add on one or more variables to represent the specific factors/drivers of interest <span class="math inline">\(Z\)</span>.</p>
</section>
<section id="extended-model-specification-1-health-as-a-discrete-variable" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="extended-model-specification-1-health-as-a-discrete-variable"><span class="header-section-number">3.6.2</span> Extended Model Specification 1: Health as a Discrete Variable</h3>
<p>Our first extension of the final foundational model specification is an example where <span class="math inline">\(Z\)</span> is a single binary health-related indicator. For this we used the variable <code>health</code>, which reports individuals’ responses to the following question:</p>
<blockquote class="blockquote">
<p>Do you have any long-standing physical or mental impairment, illness or disability? By ‘long-standing’ I mean anything that has troubled you over a period of at least 12 months or that is likely to trouble you over a period of at least 12 months.<span class="citation" data-cites="healthv">(<a href="#ref-healthv" role="doc-biblioref"><span>“Health Variable,”</span> n.d.</a>)</span></p>
</blockquote>
<p>We coded affirmative responses to this question as ‘1’, and ‘0’ otherwise, and referred to this binary coded version of the variable as <code>lt_condition</code> in our models. This discrete health extended model specification is therefore the foundational model specification plus this additional variable, i.e.</p>
<blockquote class="blockquote">
<p><code>next_status ~ this_status * sex + splines::bs(age, 5) + lt_condition</code></p>
</blockquote>
<p>To check whether the above specification is sufficient extension of the foundational model when incorporating the possible influence of LLTI, we considered an additional specification including an <code>health:sex</code> interaction. However, this interaction term did not lead to an improvement in either AIC or BIC.</p>
</section>
<section id="extended-model-specification-2-modelling-health-as-a-continuous-outcome-using-the-sf-12" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="extended-model-specification-2-modelling-health-as-a-continuous-outcome-using-the-sf-12"><span class="header-section-number">3.6.3</span> Extended Model Specification 2: Modelling health as a continuous outcome using the SF-12</h3>
<p>Our second extended model specification involved modelling health as a continuous rather than discrete variable. For this, we used summary responses from the Short Form (SF) 12, which is a 12-item questionnaire for assessing both mental and physical health asked in each wave of the UKHLS. Of the 12 items in the questionnaire, six items relate to physical health (physical functioning, physical role, bodily pain, and general health), and six items relate to mental health (energy, social functioning, emotional role, mental health) (Turner-Bowker and Hogue, 2014) (Ware et al, 1995). The scores from each of these pairs of six items are aggregated to produce separate mental and physical health component scores; the two scores are not then further aggregated to produce a single overall continuous health score.</p>
<p>For our purposes, we first standardised and normalised both the aggregate mental health and physical health component scores, so that both scores have a mean of 0 and standard deviation of 1. This is to allow us to approach using the model to estimate the contribution that health has on economic (in)activity in a similar way to that used in the first extended model specification. Let us refer to the standardised and normalised mental health component score as <span class="math inline">\(z^M\)</span> and the standardised and normalised physical health component score as <span class="math inline">\(z^P\)</span>.</p>
<p>Because health scores from the SF-12 are not further aggregated into a single overall health score, but remain separate variables, there are a number of alternative ways that they can be implemented to form the extended model specification. This includes:</p>
<ol type="1">
<li>Adding <span class="math inline">\(z^M\)</span> only</li>
<li>Adding <span class="math inline">\(z^P\)</span> only</li>
<li>Adding both <span class="math inline">\(z^M\)</span> and <span class="math inline">\(z^P\)</span> as independent terms</li>
<li>Adding both <span class="math inline">\(z^M\)</span> and <span class="math inline">\(z^P\)</span>, including an interaction term between <span class="math inline">\(z^M\)</span> and <span class="math inline">\(z^P\)</span></li>
</ol>
<p>As elsewhere, we compared these candidate extended model specifications using AIC and BIC. The model specification with the lowest (i.e.&nbsp;‘preferred’) AIC and BIC scores was the fourth specification above, i.e.&nbsp;the model including both terms with an interaction term. All above model specifications had lower AIC and BIC scores than the foundational model specification.</p>
</section>
</section>
</section>
<section id="results-developing-the-foundational-model" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results: Developing the Foundational Model</h1>
<p>As mentioned previously, the modelling approach starts with attempting to determine a foundational model specification which adequately controls for event history (<span class="math inline">\(y_t\)</span>) and demography (i.e.&nbsp;age and sex). A number of specifications are considered. These specifications differ in terms of the following parameters:</p>
<ul>
<li>Whether the specification includes an interaction between sex and current status</li>
<li>the degree of the polynomial for the spline to represent age</li>
</ul>
<p>When extracting paired observations between consecutive economic statuses between waves, and when selecting on only those observations where age and sex has been recorded, age is between 16 and 64 years of age inclusive, and both economic status at current and next wave has been successfully identified, then a total of 305,324 observations are available from the UKHLS, relating to 58,301 unique individuals. A random selection of ten observations from this dataset is as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-fnd-ex-inputs" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Ten observations selected at random for use in the foundational model specification</caption>
<thead>
<tr class="header">
<th style="text-align: right;">pidp</th>
<th style="text-align: left;">wave</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">sex</th>
<th style="text-align: left;">this_status</th>
<th style="text-align: left;">next_status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">476763647</td>
<td style="text-align: left;">d</td>
<td style="text-align: right;">42</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="even">
<td style="text-align: right;">1020258415</td>
<td style="text-align: left;">a</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">Inactive student</td>
<td style="text-align: left;">Inactive student</td>
</tr>
<tr class="odd">
<td style="text-align: right;">843280249</td>
<td style="text-align: left;">f</td>
<td style="text-align: right;">29</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="even">
<td style="text-align: right;">884384887</td>
<td style="text-align: left;">b</td>
<td style="text-align: right;">45</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="odd">
<td style="text-align: right;">408289687</td>
<td style="text-align: left;">f</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="even">
<td style="text-align: right;">544497091</td>
<td style="text-align: left;">c</td>
<td style="text-align: right;">57</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="odd">
<td style="text-align: right;">680593647</td>
<td style="text-align: left;">e</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Inactive care</td>
</tr>
<tr class="even">
<td style="text-align: right;">273117931</td>
<td style="text-align: left;">g</td>
<td style="text-align: right;">51</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="odd">
<td style="text-align: right;">139406809</td>
<td style="text-align: left;">c</td>
<td style="text-align: right;">36</td>
<td style="text-align: left;">female</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">Employed</td>
</tr>
<tr class="even">
<td style="text-align: right;">137030207</td>
<td style="text-align: left;">a</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;">Inactive other</td>
<td style="text-align: left;">Employed</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In <a href="#tbl-fnd-ex-inputs">Table&nbsp;1</a> <code>pidp</code> refers to the person identifier, which is unique and consistent across waves, <code>wave</code> is a character indicating the wave from which the variables <code>age</code>, <code>sex</code> and <code>this_status</code> have been observed and recorded. For example wave <code>a</code> is the UKHLS’s first wave, <code>d</code> the fourth wave, and <code>f</code> the sixth wave. The variable <code>next_status</code> is the economic status as observed at the wave immediately after the wave indicated in the <code>wave</code> variable: for wave <code>d</code>, this would be wave <code>e</code>, for <code>f</code>, it would be wave <code>g</code>, and so on.</p>
<p>Both <code>this_status</code> and <code>next_status</code> are seven category regroupings of the variable <code>jbstat</code> in the individual level wave-specific UKHLS datasets.</p>
<p>Below are a series of possible foundational model specifications which incorporate age, sex and event history (<code>this_status</code>) in different ways.</p>
<ul>
<li><code>fnd_00</code>: <code>next_status ~ this_status + sex + splines::bs(age, 3)</code></li>
<li><code>fnd_01</code>: <code>next_status ~ this_status + sex + splines::bs(age, 4)</code></li>
<li><code>fnd_02</code>: <code>next_status ~ this_status + sex + splines::bs(age, 5)</code></li>
<li><code>fnd_03</code>: <code>next_status ~ this_status + sex + splines::bs(age, 6)</code></li>
<li><code>fnd_04</code>: <code>next_status ~ this_status * sex + splines::bs(age, 3)</code></li>
<li><code>fnd_05</code>: <code>next_status ~ this_status * sex + splines::bs(age, 4)</code></li>
<li><code>fnd_06</code>: <code>next_status ~ this_status * sex + splines::bs(age, 5)</code></li>
<li><code>fnd_07</code>: <code>next_status ~ this_status * sex + splines::bs(age, 6)</code></li>
</ul>
<p>The first four specifications involve no interaction between <code>sex</code> and <code>this_status</code>, whereas the last four specifications inclulde an additional <code>sex:this_status</code> interaction term. The number inside the <code>bs()</code> function determines the degree of flexibility of the age spline component.</p>
<p>The penalised model fits using AIC and BIC for each of the above specifications is as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-fnd-aic-bic" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;2: AIC and BIC of eight possible foundational model specifications</caption>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">aic_rank</th>
<th style="text-align: right;">bic_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fnd_00</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">289790.9</td>
<td style="text-align: right;">290492.4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_01</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">289743.8</td>
<td style="text-align: right;">290509.1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_02</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">289722.5</td>
<td style="text-align: right;">290551.6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_03</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">289694.8</td>
<td style="text-align: right;">290587.6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_04</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">289191.0</td>
<td style="text-align: right;">290275.2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_05</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">289143.5</td>
<td style="text-align: right;">290291.5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_06</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">289122.5</td>
<td style="text-align: right;">290334.3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_07</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">289094.7</td>
<td style="text-align: right;">290370.2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From <a href="#tbl-fnd-aic-bic">Table&nbsp;2</a> we can see that, having set the number of iterations to 200 rather than the default 100, all models have converged before reaching the iteration limit. The four model specifications with interaction terms (<code>fnd_04</code> through to <code>fnd_07</code>) outpeform the model specifications without interaction terms, suggesting the interaction term should be included. However, the rank order of these specifications using AIC and BIC are reversed, with AIC suggesting the most complicated model specification <code>fnd_07</code> should be used, whereas BIC indicating the least complicated of the with-interaction term model specifications <code>fnd_04</code> should be used.</p>
<p>However only a subset of the above data contain the necessary health variables, and the foundational model specification that best fits this subset may be clearer.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-fnd-aic-bic-health" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;3: AIC and BIC for the eight candidate foundational model specification using only data which also contains health variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">aic_rank</th>
<th style="text-align: right;">bic_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fnd_00</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">289293.3</td>
<td style="text-align: right;">289994.7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_01</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">289246.7</td>
<td style="text-align: right;">290011.9</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_02</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">289225.7</td>
<td style="text-align: right;">290054.7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_03</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">289198.2</td>
<td style="text-align: right;">290091.0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_04</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">288695.9</td>
<td style="text-align: right;">289779.9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_05</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">288648.9</td>
<td style="text-align: right;">289796.7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_06</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">288628.2</td>
<td style="text-align: right;">289839.8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_07</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">288600.7</td>
<td style="text-align: right;">289876.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#tbl-fnd-aic-bic-health">Table&nbsp;3</a> shows that, with the health-variable subset of the dataset, the same results are apparent: models including interaction terms outperform those without interaction terms, but the rank order of preference differs by whether the AIC or BIC metric is used.</p>
<p>To try to resolve this, we can also look at the subset of data which contains the continuous health variables of interest. These are discussed in detail in Appendix C. They confirm that <code>fnd_06</code> is marginally preferred to other candidate model specifications, but also that there is only marginal difference in out-of-sample predictive accuracy scores between the model specifications.</p>
</section>
<section id="results-developing-the-extended-models" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Results: Developing the extended models</h1>
<p>As mentioned there are two types of extended model specification presented here, one in which health is treated as a discrete variable, and another in which health is treated as continuous variables. For both types of model we begin by detailing how the extended model specification was arrived at, before presenting the results of simulations based on the selected extended model specification</p>
<section id="modelling-health-as-a-discrete-variable" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="modelling-health-as-a-discrete-variable"><span class="header-section-number">5.1</span> Modelling Health as a Discrete Variable</h2>
<section id="model-selection" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="model-selection"><span class="header-section-number">5.1.1</span> Model selection</h3>
<p>The two following extended model specifications were considered as ways of incorporating the effect of a long-term health condition (where the variable <code>lt_condition</code> is a simple derivative of the <code>health</code> variable in the UKHLS) on labour market activity:</p>
<ul>
<li><code>mod_01</code>: <code>next_status ~ this_status * sex + splines::bs(age, 5) + lt_condition</code></li>
<li><code>mod_02</code>: <code>next_status ~ this_status * sex + splines::bs(age, 5) + lt_condition * sex</code></li>
</ul>
<p>i.e.&nbsp;the second of these two specifications allows for an interaction term between sex and condition, in addition to the interaction term between sex and <code>this_status</code> already included as part of the baseline model.</p>
<p>The penalised model fits of the two extended model specifications, along with the foundational model specification (called <code>mod_00</code> here), using AIC and BIC are shown below:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-aic-bic-hlth-discrete" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;4: AIC and BIC of the foundational model specification (mod_00) along with two candidate extended model specifications which include health as a discrete variable</caption>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">aic_rank</th>
<th style="text-align: right;">bic_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod_00</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">288652.3</td>
<td style="text-align: right;">289991.4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod_01</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">284982.5</td>
<td style="text-align: right;">286385.4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mod_02</td>
<td style="text-align: right;">138</td>
<td style="text-align: right;">284977.4</td>
<td style="text-align: right;">286444.1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From <a href="#tbl-aic-bic-hlth-discrete">Table&nbsp;4</a> we can see that both versions of the extended model specification <code>mod_01</code> and <code>mod_02</code> outperformed the foundational model specification (called <code>mod_00</code> here), suggesting health adds useful predictive information to the model. The generally more parsimonious BIC metric suggests the model without interaction terms should be used, whereas the less parsimonious AIC metric suggests the model with interaction terms should be used. Rather than engaging in another assessment round we decided to use the simpler <code>mod_01</code>, i.e.&nbsp;the extended model specification without interaction terms, as suggested by the BIC metric.</p>
</section>
<section id="model-predictions-and-simulations" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="model-predictions-and-simulations"><span class="header-section-number">5.1.2</span> Model predictions and simulations</h3>
<section id="predictive-accuracy" class="level4" data-number="5.1.2.1">
<h4 data-number="5.1.2.1" class="anchored" data-anchor-id="predictive-accuracy"><span class="header-section-number">5.1.2.1</span> Predictive accuracy</h4>
<p>The discrete health extended model specification has an average predicted model accuracy score of <code>0.7858</code>, as opposed to <code>0.7847</code> for the foundational model, when both are assessed using the data used to fit them, showing a marginal improvement in fit associated with including this variable.</p>
</section>
<section id="vignette-examples-predicted-effects-of-health" class="level4" data-number="5.1.2.2">
<h4 data-number="5.1.2.2" class="anchored" data-anchor-id="vignette-examples-predicted-effects-of-health"><span class="header-section-number">5.1.2.2</span> Vignette examples: Predicted effects of health</h4>
<p>To further demonstrate how the modelling approach generates predicted probabilities for individuals being in each of the seven mutually exclusive and exhaustive economic states at the next wave, given existing state, age, sex, and presence or absence of a long term condition, appendix C shows the predicted results given a series of vignettes, in which combinations of three different ages, two sexes, three economic statuses, and the presence or absence of a long-term condition. The individual level results from a data-based sample frame, modifying only the <code>lt_condition</code> variable for a counterfactual scenario, are what is used to produce population level estimates of the effect of <code>lt_condition</code>, and subsequently PAFs and (where there is more than one exposure variable) SAFs.</p>
</section>
<section id="population-level-estimates" class="level4" data-number="5.1.2.3">
<h4 data-number="5.1.2.3" class="anchored" data-anchor-id="population-level-estimates"><span class="header-section-number">5.1.2.3</span> Population level estimates</h4>
<section id="unweighted-sample-frame" class="level5" data-number="5.1.2.3.1">
<h5 data-number="5.1.2.3.1" class="anchored" data-anchor-id="unweighted-sample-frame"><span class="header-section-number">5.1.2.3.1</span> Unweighted sample frame</h5>
<p><a href="#tbl-hlth-discrete-pool-diffs-unweighted">Table&nbsp;5</a> shows the estimated differences in population pool predicted to be in each of the seven mutually exclusive categories using the <em>unweighted</em> sample from the last pre-COVID wave:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-hlth-discrete-pool-diffs-unweighted" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;5: The estimated effects on the relative proportion of a population in different economic activity states of a limiting long-term illness, using the last pre-pandemic sample wave and no weighting</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Status</th>
<th style="text-align: right;">base</th>
<th style="text-align: right;">counterfactual</th>
<th style="text-align: right;">Base share</th>
<th style="text-align: right;">Counter share</th>
<th style="text-align: right;">Point diff</th>
<th style="text-align: right;">Prop diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">15481.4</td>
<td style="text-align: right;">15764.2</td>
<td style="text-align: right;">0.724</td>
<td style="text-align: right;">0.738</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">1040.7</td>
<td style="text-align: right;">1097.3</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.054</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">1255.8</td>
<td style="text-align: right;">1266.6</td>
<td style="text-align: right;">0.059</td>
<td style="text-align: right;">0.059</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">1102.9</td>
<td style="text-align: right;">1197.5</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">919.6</td>
<td style="text-align: right;">366.4</td>
<td style="text-align: right;">0.043</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">-0.602</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">1437.1</td>
<td style="text-align: right;">1543.8</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.074</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">137.5</td>
<td style="text-align: right;">139.2</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.013</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The estimated effect from this model of assigning all individuals with LLTIs to not having LLTIs is to change the projected proportion of the population who are employed from 72.4% to 73.8%, a 1.3 percentage point change. This same change is projected to <em>reduce</em> the proportion of the population who are Inactive long-term sick from 4.3% to 1.7%, which is a 2.6 percentage point reduction, or in relative terms around a 60.2% reduction from the baseline population size.</p>
</section>
<section id="weighted-sample-frame" class="level5" data-number="5.1.2.3.2">
<h5 data-number="5.1.2.3.2" class="anchored" data-anchor-id="weighted-sample-frame"><span class="header-section-number">5.1.2.3.2</span> Weighted sample frame</h5>
<p><a href="#tbl-hlth-discrete-pool-diffs-weighted">Table&nbsp;6</a> the effect of weighting the wave j population using the weighting variable <code>j_indinui_xw</code> from the UKHLS.</p>
<div class="cell" data-hash="main_cache/html/tbl-hlth-discrete-pool-diffs-weighted_d773c5cdc868c3c5f0d3d351799fa763">
<div class="cell-output-display">
<div id="tbl-hlth-discrete-pool-diffs-weighted" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;6: The estimated effects on the relative proportion of a population in different economic activity states of a limiting long-term illness, using the last pre-pandemic sample wave and cross-sectional weighting for this wave</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">status</th>
<th style="text-align: right;">baseline</th>
<th style="text-align: right;">counterfactual</th>
<th style="text-align: right;">Base share</th>
<th style="text-align: right;">Counter share</th>
<th style="text-align: right;">Point diff</th>
<th style="text-align: right;">Prop diff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">15434.9</td>
<td style="text-align: right;">15741.8</td>
<td style="text-align: right;">0.722</td>
<td style="text-align: right;">0.736</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.020</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">1109.9</td>
<td style="text-align: right;">1179.9</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.063</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">1356.1</td>
<td style="text-align: right;">1368.5</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.064</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">931.2</td>
<td style="text-align: right;">1029.3</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">1016.9</td>
<td style="text-align: right;">405.5</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">-0.029</td>
<td style="text-align: right;">-0.601</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">1388.3</td>
<td style="text-align: right;">1509.6</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">137.8</td>
<td style="text-align: right;">140.4</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.019</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Using the reweighting the results are slightly different: the share of the population projected to be employed in the baseline scenario is now 72.2% (compared with 72.4%), and in the counterfactual scenario 73.6% (compared with 73.8% unweighted). The proportion of the population projected to be Inactive long-term sick is now 4.8% in the baseline scenario and 1.9% in the counterfactual scenario, i.e.&nbsp;more than a halving.</p>
</section>
</section>
<section id="paf-summary" class="level4" data-number="5.1.2.4">
<h4 data-number="5.1.2.4" class="anchored" data-anchor-id="paf-summary"><span class="header-section-number">5.1.2.4</span> PAF summary</h4>
<p>Whether using weighted or unweighted approaches, the population share projected to be Inactive long-term sick is around 60% smaller in the counterfactual scenario, where all individuals’ long-term illness status is ‘cured’, than in the baseline scenario where some proportion of the people have long-term illness flags. This suggests a population attributable fraction (PAF) of around 60%, i.e.&nbsp;60% of the pool of persons of working age who are inactive long-term sick is ‘explained by’ a limiting long-term condition.</p>
</section>
</section>
</section>
<section id="modelling-health-as-continuous-variables" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="modelling-health-as-continuous-variables"><span class="header-section-number">5.2</span> Modelling Health as Continuous Variables</h2>
<section id="model-selection-1" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="model-selection-1"><span class="header-section-number">5.2.1</span> Model selection</h3>
<p>The following model extended model specifications were considered and compared with the foundational model specification:</p>
<ul>
<li><code>mod_mh</code>: Mental health only</li>
<li><code>mod_ph</code>: Physical health only</li>
<li><code>mod_ph_mh</code>: Physical health and mental health: no interaction term</li>
<li><code>mod_phmh</code>: Physical health and mental health: interaction term</li>
</ul>
<p>The AICs and BICs of these model specifications are shown in <a href="#tbl-aic-bic-ranking-hlth-continuous">Table&nbsp;7</a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-aic-bic-ranking-hlth-continuous" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;7: AIC and BIC scores and rankings for the foundational model specification (mod_00) and four candidate extended model specifications which incorporate health as a continuous variable</caption>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">aic_rank</th>
<th style="text-align: right;">bic_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mod_00</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">249265.2</td>
<td style="text-align: right;">250588.8</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod_mh</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">247752.0</td>
<td style="text-align: right;">249138.7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mod_ph</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">245398.4</td>
<td style="text-align: right;">246785.1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">mod_ph_mh</td>
<td style="text-align: right;">138</td>
<td style="text-align: right;">243527.6</td>
<td style="text-align: right;">244977.3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mod_phmh</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;">243420.4</td>
<td style="text-align: right;">244933.1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Here the results are unequivocal: both the AIC and BIC metrics indicate the model including both mental and physical health factors, and an interaction term between them, should be used.</p>
</section>
<section id="model-predictions-and-simulations-1" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="model-predictions-and-simulations-1"><span class="header-section-number">5.2.2</span> Model predictions and simulations</h3>
<section id="predictive-accuracy-1" class="level4" data-number="5.2.2.1">
<h4 data-number="5.2.2.1" class="anchored" data-anchor-id="predictive-accuracy-1"><span class="header-section-number">5.2.2.1</span> Predictive accuracy</h4>
<p>The continuous health extended model specification has an average predicted model accuracy score of <code>0.7927</code>, as opposed to <code>0.7902</code> for the foundational model, when both are assessed using the data used to fit them, showing a marginal improvement in fit associated with including this variable.</p>
</section>
<section id="counterfactual-scenarios" class="level4" data-number="5.2.2.2">
<h4 data-number="5.2.2.2" class="anchored" data-anchor-id="counterfactual-scenarios"><span class="header-section-number">5.2.2.2</span> Counterfactual scenarios</h4>
<p>Unlike with the discrete case, there are a number of possible counterfactual scenarios in which 1 standardised unit of improvement in health has been modelled. Such health improvement could occur entirely through the mental health pathway, or entirely through the physical health pathway, or through a combination of both mental and physical health improvements, which may be biased either towards mental health or physical health. Because of this five different counterfactual scenarios are considered, which can be represented visually, as shown in <a href="#fig-genhealth">Figure&nbsp;1</a> below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-genhealth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="main_files/figure-html/fig-genhealth-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Schematic representation of continuous health improvement scenarios modelled</figcaption>
</figure>
</div>
</div>
</div>
<p>In order to ensure we are looking at the effect of the type of the driver being modified, rather than the amount of change we are making to these drivers, we need to employ a little trigonometry. If we were to modify both MH and PH by one standard unit, the total amount of change in ‘health’ would be the hypotenuse of a triangle in which both MH and PH are ‘legs’, i.e.&nbsp;<span class="math inline">\(\sqrt{1^2+1^2}\)</span> or <span class="math inline">\(\sqrt{2}\)</span>, which is <code>1.41</code> to two decimal places, and so larger than either of the previous exposure reductions being modelled. In order to work out the amount of equal change across both ‘legs’ required for a 1 unit total change across both dimensions, we therefore need to solve <span class="math inline">\(1=\sqrt{z^2+z^2}\)</span>, i.e.&nbsp;<span class="math inline">\(1=\sqrt{2z^2}\)</span>. This means <span class="math inline">\(1=2z^2\)</span>, so <span class="math inline">\(z^2=1/2\)</span>, and therefore <span class="math inline">\(z=\frac{1}{\sqrt{2}}\)</span>. In scenario 3, therefore, both MH and PH are increased by this same amount, which is <code>0.71</code> to two decimal places.</p>
<p>Four different exposure model specifications were considered:</p>
<ol type="1">
<li><code>mod_mh</code>: Mental Health only</li>
<li><code>mod_ph</code>: Physical Health only</li>
<li><code>mod_ph_mh</code>: Mental Health AND Physical Health (as independent effects)</li>
<li><code>mod_phmh</code>: Mental Health AND Physical Health, including an interaction term</li>
</ol>
</section>
<section id="population-level-estimates-1" class="level4" data-number="5.2.2.3">
<h4 data-number="5.2.2.3" class="anchored" data-anchor-id="population-level-estimates-1"><span class="header-section-number">5.2.2.3</span> Population level estimates</h4>
<section id="unweighted-sample-frame-1" class="level5" data-number="5.2.2.3.1">
<h5 data-number="5.2.2.3.1" class="anchored" data-anchor-id="unweighted-sample-frame-1"><span class="header-section-number">5.2.2.3.1</span> Unweighted sample frame</h5>
<p>The following table shows the estimated differences in population pool predicted to be in each of the seven mutually exclusive categories using the <em>unweighted</em> sample from the last pre-COVID wave:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-hlth-continuous-pool-diffs-unweighted" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;8: The estimated effects on the relative proportion of a population in different economic activity states as a result of improving health, using the last pre-pandemic sample wave and no weighting</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Status</th>
<th style="text-align: right;">base_share</th>
<th style="text-align: right;">counter_mh_only_share</th>
<th style="text-align: right;">counter_mh_bias_share</th>
<th style="text-align: right;">counter_equal_share</th>
<th style="text-align: right;">counter_ph_bias_share</th>
<th style="text-align: right;">counter_ph_only_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">0.7298824</td>
<td style="text-align: right;">0.7401458</td>
<td style="text-align: right;">0.7458463</td>
<td style="text-align: right;">0.7481795</td>
<td style="text-align: right;">0.7491036</td>
<td style="text-align: right;">0.7476440</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">0.0478886</td>
<td style="text-align: right;">0.0421595</td>
<td style="text-align: right;">0.0398184</td>
<td style="text-align: right;">0.0391064</td>
<td style="text-align: right;">0.0391670</td>
<td style="text-align: right;">0.0406065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">0.0584233</td>
<td style="text-align: right;">0.0587900</td>
<td style="text-align: right;">0.0603937</td>
<td style="text-align: right;">0.0611442</td>
<td style="text-align: right;">0.0614774</td>
<td style="text-align: right;">0.0612389</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">0.0480222</td>
<td style="text-align: right;">0.0485134</td>
<td style="text-align: right;">0.0476570</td>
<td style="text-align: right;">0.0470484</td>
<td style="text-align: right;">0.0465061</td>
<td style="text-align: right;">0.0459745</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">0.0409085</td>
<td style="text-align: right;">0.0345194</td>
<td style="text-align: right;">0.0303162</td>
<td style="text-align: right;">0.0287902</td>
<td style="text-align: right;">0.0285110</td>
<td style="text-align: right;">0.0302655</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">0.0685888</td>
<td style="text-align: right;">0.0701365</td>
<td style="text-align: right;">0.0703249</td>
<td style="text-align: right;">0.0700583</td>
<td style="text-align: right;">0.0694528</td>
<td style="text-align: right;">0.0682176</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">0.0062862</td>
<td style="text-align: right;">0.0057355</td>
<td style="text-align: right;">0.0056436</td>
<td style="text-align: right;">0.0056730</td>
<td style="text-align: right;">0.0057820</td>
<td style="text-align: right;">0.0060529</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Even though each of the counterfactual scenarios are the same in terms of the <em>amount</em> of change they represent relative to the baseline, they differ in terms of the relative contribution of mental or physical health improvement pathways towards this overall improvement.</p>
<p>In terms of projected effect on the share of the population Inactive - long-term sick, the scenario <code>counter_ph_bias</code> apepars to have the largest effect, reducing the share of the population in this state from 4.09% in the baseline scenario to 2.85%. As factors explaining this state are of particular interest we will now focus on this specific counterfactual scenario when comparing with the baseline. The absolute and relative differences between the baseline and this counterfactual scenario are as shown in <a href="#tbl-hlth-continuous-pool-diffs-unweighted-summarised">Table&nbsp;9</a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-hlth-continuous-pool-diffs-unweighted-summarised" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;9: Relative and absolute differences in economic activity state pool sizes between baseline and counterfactual scenario in which health (based to PH) has been improved. Unweighted dataframe.</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Status</th>
<th style="text-align: right;">base_share</th>
<th style="text-align: right;">counter_ph_bias_share</th>
<th style="text-align: right;">point_difference</th>
<th style="text-align: right;">prop_difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">0.7298824</td>
<td style="text-align: right;">0.7491036</td>
<td style="text-align: right;">0.0192212</td>
<td style="text-align: right;">0.0263347</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">0.0478886</td>
<td style="text-align: right;">0.0391670</td>
<td style="text-align: right;">-0.0087216</td>
<td style="text-align: right;">-0.1821224</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">0.0584233</td>
<td style="text-align: right;">0.0614774</td>
<td style="text-align: right;">0.0030541</td>
<td style="text-align: right;">0.0522755</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">0.0480222</td>
<td style="text-align: right;">0.0465061</td>
<td style="text-align: right;">-0.0015161</td>
<td style="text-align: right;">-0.0315705</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">0.0409085</td>
<td style="text-align: right;">0.0285110</td>
<td style="text-align: right;">-0.0123975</td>
<td style="text-align: right;">-0.3030537</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">0.0685888</td>
<td style="text-align: right;">0.0694528</td>
<td style="text-align: right;">0.0008639</td>
<td style="text-align: right;">0.0125958</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">0.0062862</td>
<td style="text-align: right;">0.0057820</td>
<td style="text-align: right;">-0.0005041</td>
<td style="text-align: right;">-0.0801973</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From <a href="#tbl-hlth-continuous-pool-diffs-unweighted-summarised">Table&nbsp;9</a> we can see that health, as operationalised in this way - as a one standardised unit improvement along both mental and physical health, but biased towards physical health improvement, would lead to a decrease in the share of the population who are Inactive long-term sick from around 4.09% to 2.85%, or a difference of around 30%. This could be interpreted as an estimated PAF of the Inactive long-term sick population attributable to poor health based on this continuous health variable approach, although it is not directly comparable with the approach taken in the discrete health scenario previously.</p>
</section>
<section id="weighted-sample-frame-1" class="level5" data-number="5.2.2.3.2">
<h5 data-number="5.2.2.3.2" class="anchored" data-anchor-id="weighted-sample-frame-1"><span class="header-section-number">5.2.2.3.2</span> Weighted sample frame</h5>
<p><a href="#tbl-hlth-continuous-pool-diffs-weighted">Table&nbsp;10</a> shows the effect of weighting the wave j population using the weighting variable <code>j_indinui_xw</code> from the UKHLS, with a focus on the scenario that leads to the greatest apparent effect on Inactive long-term sick, namely the <code>ph_bias</code> scenario.</p>
<div class="cell" data-hash="main_cache/html/tbl-hlth-continuous-pool-diffs-weighted_93219198f6dc0c68166747b5b4a16073">
<div class="cell-output-display">
<div id="tbl-hlth-continuous-pool-diffs-weighted" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;10: The estimated effects on the relative proportion of a population in different economic activity states as a result of improving health, using the last pre-pandemic sample wave and cross-sectional weighting</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">status</th>
<th style="text-align: right;">baseline</th>
<th style="text-align: right;">counterfactual</th>
<th style="text-align: right;">base_share</th>
<th style="text-align: right;">counter_share</th>
<th style="text-align: right;">point_difference</th>
<th style="text-align: right;">prop_difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">14740.1055</td>
<td style="text-align: right;">15135.9847</td>
<td style="text-align: right;">0.7263283</td>
<td style="text-align: right;">0.7458355</td>
<td style="text-align: right;">0.0195072</td>
<td style="text-align: right;">0.0268573</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">1038.6712</td>
<td style="text-align: right;">854.8404</td>
<td style="text-align: right;">0.0511812</td>
<td style="text-align: right;">0.0421228</td>
<td style="text-align: right;">-0.0090584</td>
<td style="text-align: right;">-0.1769866</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">1290.2883</td>
<td style="text-align: right;">1359.3788</td>
<td style="text-align: right;">0.0635798</td>
<td style="text-align: right;">0.0669843</td>
<td style="text-align: right;">0.0034045</td>
<td style="text-align: right;">0.0535465</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">846.4108</td>
<td style="text-align: right;">821.2700</td>
<td style="text-align: right;">0.0417074</td>
<td style="text-align: right;">0.0404686</td>
<td style="text-align: right;">-0.0012388</td>
<td style="text-align: right;">-0.0297029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">913.0123</td>
<td style="text-align: right;">644.4313</td>
<td style="text-align: right;">0.0449893</td>
<td style="text-align: right;">0.0317548</td>
<td style="text-align: right;">-0.0132345</td>
<td style="text-align: right;">-0.2941702</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">1336.4968</td>
<td style="text-align: right;">1359.0392</td>
<td style="text-align: right;">0.0658567</td>
<td style="text-align: right;">0.0669675</td>
<td style="text-align: right;">0.0011108</td>
<td style="text-align: right;">0.0168668</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">129.0151</td>
<td style="text-align: right;">119.0557</td>
<td style="text-align: right;">0.0063573</td>
<td style="text-align: right;">0.0058665</td>
<td style="text-align: right;">-0.0004908</td>
<td style="text-align: right;">-0.0771960</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can see from <a href="#tbl-hlth-continuous-pool-diffs-weighted">Table&nbsp;10</a> that, using the reweighting approach, the proportion projected to be Inactive long-term sick is 4.50% in the baseline scenario, compared to 3.18% in the counterfactual scenario. This is a relative decline of 29.4%, which is only marginally different from the 30.4% estimate produced when no weighting was used.</p>
</section>
</section>
<section id="sequential-attributable-fraction-estimation" class="level4" data-number="5.2.2.4">
<h4 data-number="5.2.2.4" class="anchored" data-anchor-id="sequential-attributable-fraction-estimation"><span class="header-section-number">5.2.2.4</span> Sequential attributable fraction estimation</h4>
<p>The same model can be used to estimate sequential attributable fractions (SAFs) associated with a given marginal change in health status given that another change in health status has already occurred. We can do this by modelling the four following scenarios:</p>
<ul>
<li><strong>O</strong> Baseline scenario: No change to mental or physical health scores</li>
<li><strong>P</strong> PH only: Physical health improved by one standardised unit; mental health unchanged</li>
<li><strong>M</strong> MH only: Mental health improved by one standardised unit; physical health unchanged</li>
<li><strong>B</strong> Both: Both mental health and physical health <em>each</em> improved by one standardised unit.</li>
</ul>
<p>Note that scenarios <strong>O</strong>, <strong>P</strong>, and <strong>M</strong> have already been modelled; only scenario <strong>B</strong> remains to be modelled. Whereas previously each counterfactual scenario modelled involved a 1 standardised unit change from health states in the baseline scenario, but with different degrees of bias towards either physical or mental health change, in the <strong>B</strong> scenario the total change in health is greater, being 1 unit in the MH direction and 1 unit in the PH direction. If both MH and PH are considered orthogonal dimensions of health in general, and after standardising can be considered to share a common scale, then the total amount of health improvement represented in scenario <strong>B</strong> is therefore <span class="math inline">\(\sqrt{1^2 + 1^2}\)</span>, or around 1.41 standardised units of health improvements.</p>
<p>The aim of the SAF approach is to estimated the additional effect that a MH improvement has on the outcome of interest (Inactive long-term sick) if a PH improvement had already occurred; or of a PH improvement if a MH improvement had already occurred. It does this by using differences in outcomes by scenario to understand the following two pathways of health improvement:</p>
<ul>
<li><span class="math inline">\(O \rightarrow P \rightarrow B\)</span></li>
<li><span class="math inline">\(O \rightarrow M \rightarrow B\)</span></li>
</ul>
<p>From the perspective of the first pathway, scenario <strong>B</strong> represents the addition of MH, whereas from the perspective of the second pathway, scenario <strong>B</strong> represents the addition of PH. These scenarios are shown graphically in <a href="#fig-genhealth-saf">Figure&nbsp;2</a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-genhealth-saf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="main_files/figure-html/fig-genhealth-saf-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Schematic representation of continuous health improvement scenarios modelled for SAFs</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-hlth-continuous-6ool-diffs-saf" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;11: The estimated economic activity state pool proportions in either the no-health-improvement scenario (O), improving MH only (M), improving PH only (P), or improving both MH and PH (B)</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">state</th>
<th style="text-align: right;">O (Original)</th>
<th style="text-align: right;">M (MH Only)</th>
<th style="text-align: right;">P (PH Only)</th>
<th style="text-align: right;">B (Both)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">0.7298824</td>
<td style="text-align: right;">0.7401458</td>
<td style="text-align: right;">0.7476440</td>
<td style="text-align: right;">0.7542151</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">0.0478886</td>
<td style="text-align: right;">0.0421595</td>
<td style="text-align: right;">0.0406065</td>
<td style="text-align: right;">0.0360063</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive student</td>
<td style="text-align: right;">0.0584233</td>
<td style="text-align: right;">0.0587900</td>
<td style="text-align: right;">0.0612389</td>
<td style="text-align: right;">0.0624433</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive care</td>
<td style="text-align: right;">0.0480222</td>
<td style="text-align: right;">0.0485134</td>
<td style="text-align: right;">0.0459745</td>
<td style="text-align: right;">0.0465777</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">0.0409085</td>
<td style="text-align: right;">0.0345194</td>
<td style="text-align: right;">0.0302655</td>
<td style="text-align: right;">0.0243904</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inactive retired</td>
<td style="text-align: right;">0.0685888</td>
<td style="text-align: right;">0.0701365</td>
<td style="text-align: right;">0.0682176</td>
<td style="text-align: right;">0.0709667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inactive other</td>
<td style="text-align: right;">0.0062862</td>
<td style="text-align: right;">0.0057355</td>
<td style="text-align: right;">0.0060529</td>
<td style="text-align: right;">0.0054004</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From <strong>?@tbl-hlth-continuous-pool-diffs-saf</strong> we can see that, in the baseline scenario, 72.99% of the population are projected to be employed. When mental health alone is improved (scenario <strong>M</strong>) this increases to 74.01%. When physical health alone is improved (scenario <strong>P</strong>) this increases to 74.76%. When both physical and mental health are improved (scenario <strong>B</strong>) this increases to 75.42%.</p>
<p>So, what is the effect of mental health on the proportion employed? This question could either be answered from the perspective of the <span class="math inline">\(O \rightarrow M \rightarrow B\)</span> pathway, or from the perspective of the <span class="math inline">\(O \rightarrow P \rightarrow B\)</span> pathway. From the perspective of the first pathway, the effect of improving mental health is projected to increase the proportion employed by 1.03% points (<span class="math inline">\(O \rightarrow M\)</span>). From the perspective of the second pathway, the effect of improving mental health is projected to increase it by 0.66% points (<span class="math inline">\(P \rightarrow B\)</span>).</p>
<p>The difference between PAFs and SAFs, and so the importance of modelling marginal effects along sequences, is even easier to understand if looking at projected changes in the proportion Inactive long-term sick in each of the four scenarios. The size of this subpopulation is reduced by 0.64% points if going along the <span class="math inline">\(O \rightarrow M\)</span> pathway, equivalent to a 15.62% reduction in the baseline subpopulation size. And the size of the subpopulation is reduced by 1.06% points if going along the <span class="math inline">\(O \rightarrow P\)</span> pathway, equivalent to a 26.02% reduction in the baseline subpopulation size.</p>
<p>From a PAF-like perspective, we might be inclined to suggest therefore that 15.62% of Inactive long-term sick can be attributed to poor mental health, and 26.02% can be attributed to poor physical health. However, this it would be incorrect to assume that the amount attributable to both poor physical health and poor mental health is the sum of these two proportions, or 41.63%. Instead, the difference in subpopulation proportions when going along the <span class="math inline">\(O \rightarrow B\)</span> pathway is 1.65% points, which is a 40.38% proportionate reduction from the baseline scenario subpopulation size. This difference, from 41.63% to 40.38%, though somewhat small in this example, illustrates why the effect of multiple factors in combination will tend to be smaller than the sum of the individual effects of specific factors, and hence how SAFs differ from PAFs.</p>
</section>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussion</h1>
<section id="summary-of-key-findings" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="summary-of-key-findings"><span class="header-section-number">6.1</span> Summary of Key Findings</h2>
<p>This paper has shown how a modelling framework, utilising multinomial logistic regression and using data from the UKHLS, can simulate the distributions of persons of working age in different economic activity states under different scenarios. This approach allows for fine-grained controls for the effects of demography and event history, enabling the estimation of the <em>ceteris paribus</em> effects of specific exposure factors on these distributions. From this, the framework can produce changes in population pool sizes, such as relative changes in the proportion of the population who are economically inactive, which are interpretable as PAFs (Population Attributable Fractions) and SAFs (Sequential Attributable Fractions).</p>
</section>
<section id="interpretation-of-findings" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interpretation-of-findings"><span class="header-section-number">6.2</span> Interpretation of Findings</h2>
<p>The examples of exposures demonstrated in this paper relate to health, with one example of modeling health as a discrete variable and another as a continuous variable. These two approaches are not directly comparable; the discrete health variable models removing ‘bad health’ from afflicted individuals, while the continuous health examples involve improving everyone’s health by an equal amount. This discrepancy explains why the two approaches produce different PAF-like estimates for the contribution of ‘health’ to economic inactivity due to long-term sickness: approximately 60% using the discrete example and around 30% for the continuous examples. However, the primary focus of this paper is methodological rather than providing definitive estimates of specific exposures’ contributions to various economic activity state population sizes.</p>
</section>
<section id="comparison-with-previous-research" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="comparison-with-previous-research"><span class="header-section-number">6.3</span> Comparison with Previous Research</h2>
<p>[The provided content does not contain a direct comparison with previous research. A comparison of findings with prior studies, discussing consistency or discrepancies, should be included here.]</p>
</section>
<section id="implications" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="implications"><span class="header-section-number">6.4</span> Implications</h2>
<p>The framework presented allows for various potential applications. It can be expanded by incorporating additional individual and household-level factors such as qualifications, housing tenure, and household composition. Moreover, by using special license access to more detailed UKHLS data, researchers can include smaller area geography identifiers and local area-level variables, further expanding the framework’s utility for exploring and estimating factors affecting economic activity status. This broad applicability suggests significant potential for future research, particularly in areas like health interventions, where the framework could simulate the effects of different types and scales of interventions over varying time periods.</p>
</section>
<section id="limitations" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="limitations"><span class="header-section-number">6.5</span> Limitations</h2>
<p>The data used for the model are from pre-pandemic years, and it is possible that the relationship between health and economic (in)activity has changed in the UK due to the pandemic and subsequent factors. For example, historically, most illness-related economic inactivity was due to physical health issues. Still, there has been substantial growth in mental health-related inactivity, especially among younger working-age adults. Additionally, the UKHLS’s complex research design, while allowing for longitudinal tracking, may lead to decreasing representativeness over time, necessitating the use of cross-sectional sample weights. While these weights were used in the model, the potential impact of attrition on representativeness, particularly concerning specific UK regions, remains a limitation.</p>
</section>
<section id="future-research-directions" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="future-research-directions"><span class="header-section-number">6.6</span> Future Research Directions</h2>
<p>Further research could investigate the degree of dependence PAF-like estimates of exposures have on the choice of foundational model specifications. This could produce estimates of structural model dependence, contributing to understanding the reliability of such estimates. Additionally, there is potential for expanding the model to include absorbing states like death or retirement, especially for multi-period simulations. Investigating the implications of these absorbing states, as well as the trade-offs involved in adding them to the model, could be a valuable area of future study.</p>
</section>
<section id="conclusion" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.7</span> Conclusion</h2>
<p>This paper has rigorously described the development and operationalization of a modeling framework that simulates the effects of various exposures on economic activity states. It has highlighted the methodological contributions of the framework and its potential applications for understanding the determinants of economic activity and inactivity. The use of R and the availability of the code as open-source resources enhance the framework’s accessibility, facilitating its adoption and refinement by other researchers.</p>
<p>[The content here is missing a direct summary and final reflection that would typically be part of a conclusion, emphasizing the broader contribution of the study to the field.]</p>
</section>
</section>
<section id="references" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-åhs2006" class="csl-entry" role="listitem">
Åhs, Annika M. H., and Ragnar Westerling. 2006. <span>“Mortality in Relation to Employment Status During Different Levels of Unemployment.”</span> <em>Scandinavian Journal of Public Health</em> 34 (2): 159–67. <a href="https://doi.org/10.1080/14034940510032374">https://doi.org/10.1080/14034940510032374</a>.
</div>
<div id="ref-akaike1974" class="csl-entry" role="listitem">
Akaike, H. 1974. <span>“A New Look at the Statistical Model Identification.”</span> <em>IEEE Transactions on Automatic Control</em> 19 (6): 716–23. <a href="https://doi.org/10.1109/TAC.1974.1100705">https://doi.org/10.1109/TAC.1974.1100705</a>.
</div>
<div id="ref-anyadike-danes2008" class="csl-entry" role="listitem">
Anyadike-Danes, Michael, and Duncan McVicar. 2008. <span>“Has the Boom in Incapacity Benefit Claimant Numbers Passed Its Peak?”</span> <em>Fiscal Studies</em> 29 (4): 415434.
</div>
<div id="ref-beatty2013" class="csl-entry" role="listitem">
Beatty, Christina, and Steve Fothergill. 2013. <span>“Disability Benefits in the UK: An Issue of Health or Jobs?”</span> In, edited by Colin Lindsay and Donald Houston, 15–32. London: Palgrave Macmillan UK. <a href="http://link.springer.com/10.1057/9781137314277_2">http://link.springer.com/10.1057/9781137314277_2</a>.
</div>
<div id="ref-benzeval2023" class="csl-entry" role="listitem">
Benzeval, Michaela, Thomas F. Crossley, and Edith Aguirre. 2023. <span>“A Symposium on Understanding Society, the UK Household Longitudinal Study: Introduction.”</span> <em>Fiscal Studies</em> 44 (4): 317–40. <a href="https://doi.org/10.1111/1475-5890.12355">https://doi.org/10.1111/1475-5890.12355</a>.
</div>
<div id="ref-berthoud2007" class="csl-entry" role="listitem">
Berthoud, Richard. 2007. <span>“Work-Rich and Work-Poor: Three Decades of Change.”</span> <a href="https://www.jrf.org.uk/work/work-rich-and-work-poor-three-decades-of-change">https://www.jrf.org.uk/work/work-rich-and-work-poor-three-decades-of-change</a>.
</div>
<div id="ref-brown2012" class="csl-entry" role="listitem">
Brown, Judith, Evangelia Demou, Madeleine Ann Tristram, Harper Gilmour, Kaveh A Sanati, and Ewan B Macdonald. 2012. <span>“Employment Status and Health: Understanding the Health of the Economically Inactive Population in Scotland.”</span> <em>BMC Public Health</em> 12 (1): 327. <a href="https://doi.org/10.1186/1471-2458-12-327">https://doi.org/10.1186/1471-2458-12-327</a>.
</div>
<div id="ref-dar2015" class="csl-entry" role="listitem">
Dar, Aliyah. 2015. <span>“Why Are People Economically Inactive?”</span> <a href="https://commonslibrary.parliament.uk/why-are-people-economically-inactive/">https://commonslibrary.parliament.uk/why-are-people-economically-inactive/</a>.
</div>
<div id="ref-dey-chowdhury2022" class="csl-entry" role="listitem">
Dey-Chowdhury, Sunit, and Sapphira Thorne. 2022. <span>“Worker Movements and Economic Inactivity in the UK: 2018 to 2022.”</span> <a href="https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/articles/workermovementsandinactivityintheuk/2018to2022">https://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/articles/workermovementsandinactivityintheuk/2018to2022</a>.
</div>
<div id="ref-healthv" class="csl-entry" role="listitem">
<span>“Health Variable.”</span> n.d. <a href="https://www.understandingsociety.ac.uk/documentation/mainstage/variables/health/">https://www.understandingsociety.ac.uk/documentation/mainstage/variables/health/</a>.
</div>
<div id="ref-herz" class="csl-entry" role="listitem">
Herz, Benedict, and Thijs van Rens. n.d. <span>“The Labor Market in the UK, 2000-2019.”</span> <a href="https://wol.iza.org/uploads/articles/524/pdfs/the-labor-market-in-the-uk.pdf">https://wol.iza.org/uploads/articles/524/pdfs/the-labor-market-in-the-uk.pdf</a>.
</div>
<div id="ref-howdoes2023" class="csl-entry" role="listitem">
<span>“How Does Economic Inactivity Compare Across Advanced Economies?”</span> 2023. <a href="https://obr.uk/box/how-does-economic-inactivity-compare-across-advanced-economies/">https://obr.uk/box/how-does-economic-inactivity-compare-across-advanced-economies/</a>.
</div>
<div id="ref-hyndman2021" class="csl-entry" role="listitem">
Hyndman, Robert, and George Athanasopoulos. 2021. <em>Forecasting: Principles and Practice</em>. Third Edition. <a href="https://otexts.com/fpp3/">https://otexts.com/fpp3/</a>.
</div>
<div id="ref-kim2015" class="csl-entry" role="listitem">
Kim, Ji Man, Nak-Hoon Son, Eun-Cheol Park, Chung Mo Nam, Tae Hyun Kim, and Woo-Hyun Cho. 2015. <span>“The Relationship Between Changes in Employment Status and Mortality Risk Based on the Korea Labor and Income Panel Study (2003-2008).”</span> <em>Asia Pacific Journal of Public Health</em> 27 (2): NP993–1001. <a href="https://doi.org/10.1177/1010539513486923">https://doi.org/10.1177/1010539513486923</a>.
</div>
<div id="ref-king2000" class="csl-entry" role="listitem">
King, Gary, Michael Tomz, and Jason Wittenberg. 2000. <span>“Making the Most of Statistical Analyses: Improving Interpretation and Presentation.”</span> <em>American Journal of Political Science</em> 44 (2): 347. <a href="https://doi.org/10.2307/2669316">https://doi.org/10.2307/2669316</a>.
</div>
<div id="ref-labourm" class="csl-entry" role="listitem">
<span>“Labour Market Overview, UK: August 2024.”</span> n.d. <a href="https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/august2024">https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/august2024</a>.
</div>
<div id="ref-labourm2020" class="csl-entry" role="listitem">
<span>“Labour Market Overview, UK: October 2020.”</span> 2020. ONS.
</div>
<div id="ref-machin2023" class="csl-entry" role="listitem">
Machin, Steven, and Jonathan Wadsworth. 2023. <span>“The Trouble with Inactivity.”</span> <a href="https://cep.lse.ac.uk/_NEW/publications/abstract.asp?index=10314#:~:text=Inactivity%20is%20strongly%20concentrated%20on,themselves%20as%20the%20economy%20recovers.">https://cep.lse.ac.uk/_NEW/publications/abstract.asp?index=10314#:~:text=Inactivity%20is%20strongly%20concentrated%20on,themselves%20as%20the%20economy%20recovers.</a>
</div>
<div id="ref-mccloud2023" class="csl-entry" role="listitem">
McCloud, Tayla, Strahil Kamenov, Claire Callender, Glyn Lewis, and Gemma Lewis. 2023. <span>“The Association Between Higher Education Attendance and Common Mental Health Problems Among Young People in England: Evidence from Two Population-Based Cohorts.”</span> <em>The Lancet Public Health</em> 8 (10): e811–19. <a href="https://doi.org/10.1016/S2468-2667(23)00188-3">https://doi.org/10.1016/S2468-2667(23)00188-3</a>.
</div>
<div id="ref-multinom2017" class="csl-entry" role="listitem">
<span>“Multinomial Logistic Regression Model Specification.”</span> 2017, October. <a href="https://zeligproject.org/docs/articles/zeligchoice_mlogit#model">https://zeligproject.org/docs/articles/zeligchoice_mlogit#model</a>.
</div>
<div id="ref-platt2021" class="csl-entry" role="listitem">
Platt, Lucinda, Gundi Knies, Renee Luthra, Alita Nandi, and Michaela Benzeval. 2021. <span>“Understanding Society at 10 Years.”</span> <em>European Sociological Review</em> 36 (6): 976–88. <a href="https://doi.org/10.1093/esr/jcaa031">https://doi.org/10.1093/esr/jcaa031</a>.
</div>
<div id="ref-plotnikova2020" class="csl-entry" role="listitem">
Plotnikova, Maria. 2020. <span>“Explaining Spatial Patterns of Incapacity Benefit Claimant Rolls.”</span> <em>Romanian Journal of Regional Science</em> 14 (2): 35–48. <a href="https://ideas.repec.org/a/rrs/journl/v14y2020i2p35-48.html">https://ideas.repec.org/a/rrs/journl/v14y2020i2p35-48.html</a>.
</div>
<div id="ref-roberts2022" class="csl-entry" role="listitem">
Roberts, Jennifer, and Karl Taylor. 2022. <span>“New Evidence on Disability Benefit Claims in Britain: The Role of Health and the Local Labour Market.”</span> <em>Economica</em> 89 (353): 131–60. <a href="https://doi.org/10.1111/ecca.12382">https://doi.org/10.1111/ecca.12382</a>.
</div>
<div id="ref-roelfs2011" class="csl-entry" role="listitem">
Roelfs, David J., Eran Shor, Karina W. Davidson, and Joseph E. Schwartz. 2011. <span>“Losing Life and Livelihood: A Systematic Review and Meta-Analysis of Unemployment and All-Cause Mortality.”</span> <em>Social Science &amp; Medicine</em> 72 (6): 840–54. <a href="https://doi.org/10.1016/j.socscimed.2011.01.005">https://doi.org/10.1016/j.socscimed.2011.01.005</a>.
</div>
<div id="ref-schwarz1978" class="csl-entry" role="listitem">
Schwarz, Gideon. 1978. <span>“Estimating the Dimension of a Model.”</span> <em>The Annals of Statistics</em> 6 (2). <a href="https://doi.org/10.1214/aos/1176344136">https://doi.org/10.1214/aos/1176344136</a>.
</div>
<div id="ref-tinson2022" class="csl-entry" role="listitem">
Tinson, Adam, Alice Major, and David Finch. 2022. <span>“Is Poor Health Driving a Rise in Economic Inactivity?”</span> <a href="https://www.health.org.uk/news-and-comment/charts-and-infographics/is-poor-health-driving-a-rise-in-economic-inactivity?gad_source=1&amp;gclid=Cj0KCQjwh7K1BhCZARIsAKOrVqHZkWmCrptsKC8mSixh0US77N0oR3BF6ddtCmPxFAWew3P6PkOhsMYaAg3-EALw_wcB">https://www.health.org.uk/news-and-comment/charts-and-infographics/is-poor-health-driving-a-rise-in-economic-inactivity?gad_source=1&amp;gclid=Cj0KCQjwh7K1BhCZARIsAKOrVqHZkWmCrptsKC8mSixh0US77N0oR3BF6ddtCmPxFAWew3P6PkOhsMYaAg3-EALw_wcB</a>.
</div>
<div id="ref-ware1996" class="csl-entry" role="listitem">
Ware, J., M. Kosinski, and S. D. Keller. 1996. <span>“A 12-Item Short-Form Health Survey: construction of scales and preliminary tests of reliability and validity.”</span> <em>Medical Care</em> 34 (3): 220–33. <a href="https://doi.org/10.1097/00005650-199603000-00003">https://doi.org/10.1097/00005650-199603000-00003</a>.
</div>
<div id="ref-wilson2015" class="csl-entry" role="listitem">
Wilson, Rhonda L., G. Glenn Wilson, and Kim Usher. 2015. <span>“Rural Mental Health Ecology: A Framework for Engaging with Mental Health Social Capital in Rural Communities.”</span> <em>EcoHealth</em> 12 (3): 412–20. <a href="https://doi.org/10.1007/s10393-015-1037-0">https://doi.org/10.1007/s10393-015-1037-0</a>.
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="appendices" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Appendices</h1>
<section id="appendix-a-further-discussion-of-conditions-the-model-needs-to-satisfy" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="appendix-a-further-discussion-of-conditions-the-model-needs-to-satisfy"><span class="header-section-number">8.1</span> Appendix A: Further discussion of conditions the model needs to satisfy</h2>
<p>Condition (2) suggests that we should include economic (in)activity status at time <span class="math inline">\(T\)</span> as a predictor in our model, where the model response is economic (in)activity status at time <span class="math inline">\(T+1\)</span>. This inclusion of current state (at time <span class="math inline">\(T\)</span>) as a predictor of next state (time <span class="math inline">\(T+1\)</span>) means our model is Markovian, in that the influence of recent history is considered an important predictor of current status, but the longer-term history (such as from two or more time periods ago) is only considered to have influenced state at time <span class="math inline">\(T+1\)</span> through its influence on state T. This modelling approach can also be considered a discrete-state analogue of an autoregressive <span class="math inline">\(AR(1)\)</span> model in time series data, though Markovian is a more common way of conceptualising this type of model structure when working with mutually exclusive and discrete states and state transitions between time periods.</p>
<p>Condition (3), when combined with condition (1), suggests that a somewhat generic, generalisable and flexible functional form for capturing the types of influence that age can have on the probabilities of being in each of the seven mutually exclusive states. Call this functional form s(age). Potential candidates for this flexible functional form s(.) include polynomial functions, which are parametric, and spline functions, which are semi-parametric. This functional form should be sufficiently flexible as to be appropriate for all seven age-state schedules, but not so flexible that the number of parameters required to fit it are too large, or the risk of model over-fitting too great.</p>
<p>Condition (4) suggests that sex should be considered as a predictor variable in the model. It could either be included as an independent, non-interacting predictor, or also as a factor which interacts with other factors also included in the model. When considering interaction effects, a standard strategy for determining whether an interaction term is required should be adopted to make this determination.</p>
<p>Condition (5) suggests that, in addition to including the factors implied by conditions 2-4 in the model, it should be possible to decide to add additional variables to this basic specification, which allows for the effect of these additional variables on economic (in)activity states to be estimated, assuming conditions 2-4 are adequately controlled for. Within this paper, we refer to the model that includes current status (condition 2), age (condition 3) and sex (condition 4) as our foundational model, and models which add one or more additional variables of interest to the predictor side of the model as our extended models. It is by comparing scenarios in an extended model, where the variable or variables of interest are changed to one of two conditions, but the foundational model variables are kept constant, that we will be able to produce estimates of the contribution of these variables of interest to economic (in)activity states overall.</p>
</section>
<section id="appendix-b-further-discussion-of-generalised-linear-modelling-and-model-simulation-considerations" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="appendix-b-further-discussion-of-generalised-linear-modelling-and-model-simulation-considerations"><span class="header-section-number">8.2</span> Appendix B: Further discussion of generalised linear modelling and model simulation considerations</h2>
<p>A statistical model can be thought of, fundamentally, as a simplified and stylized representation of a data generation process. This involves i) defining a model, which contains various parameters to be determined; and ii) using a dataset to calibrate the model parameters. A model is a way of specifying a relationship between predictor variables, usually referred to as <span class="math inline">\(X\)</span>, and response variables, usually referred to as <span class="math inline">\(y\)</span>. The model structure determines how many model parameters are to be estimated, and the process of producing model parameter estimates usually involves attempting to minimize some kind of loss function which relates the conditional predictions from a model <span class="math inline">\(Y|X\)</span> to the observed outcome values <span class="math inline">\(y\)</span>.</p>
<section id="overview-of-what-models-contain" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="overview-of-what-models-contain"><span class="header-section-number">8.2.1</span> Overview of what models contain</h3>
<p>Almost all statistical models can be considered specific instances of a generalised linear model (GLM) specification as described below:</p>
<p><span class="math display">\[
Y_i∼f(θ_i,\alpha), θ_i=g(X_i,\beta)
\]</span></p>
<p>(See eqn 1 of <span class="citation" data-cites="king2000">King, Tomz, and Wittenberg (<a href="#ref-king2000" role="doc-biblioref">2000</a>)</span>)</p>
<p>Where <span class="math inline">\(Y_i\)</span> represents a model-predicted value for the ith observation of a dataset, <span class="math inline">\(f(.,.)\)</span> a stochastic function, <span class="math inline">\(g(.,.)\)</span> a systematic or linking function, <span class="math inline">\(X_i\)</span> a row of predictor variables corresponding to the ith observation of the data, <span class="math inline">\(θ_i\)</span> the result of applying the linking function to <span class="math inline">\(X_i\)</span> , and <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> parameters, for <span class="math inline">\(f(.,.)\)</span> and <span class="math inline">\(g(.,.)\)</span> respectively, to be determined either analytically or numerically.</p>
<p>The estimation of parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> usually involves optimising some loss function <span class="math inline">\(L(Y, y)\)</span> where <span class="math inline">\(Y\)</span> represents model predictions and <span class="math inline">\(y\)</span> the corresponding observed outcomes from the data. This loss function is usually based on maximum likelihood identification.</p>
<p>Note that the GLM specification above is generic enough that it covers cases where <span class="math inline">\(\theta_i\)</span>, <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(y_i\)</span> are vectors of length <span class="math inline">\(k\)</span>, rather than scalars (single values), and so <span class="math inline">\(\theta\)</span>, <span class="math inline">\(Y\)</span> and <span class="math inline">\(y\)</span> are matrices of dimensions <span class="math inline">\(N\)</span> by <span class="math inline">\(k\)</span> (where <span class="math inline">\(N\)</span> represents the number of observations, typically rows, in the dataset). Models where these quantities are vectors can be called multivariate regression models or vector GLMs.</p>
<p>Within this paper, we use multinomial logistic regression, which can be thought of as a vectorised extension of standard logistic regression. For standard logistic regression we code an outcome as either 0 or 1 for each observation. This is appropriate where there are two and only two mutually exclusive states that an outcome can take. The standard logistic regression looks as follows:</p>
<p><span class="math display">\[
Y_i ∼ Bernoulli(\pi_i ) , π_i = \frac{1}{(1 + e^{-X_i \beta } )}
\]</span></p>
<p>(From eqn 3 of <span class="citation" data-cites="king2000">King, Tomz, and Wittenberg (<a href="#ref-king2000" role="doc-biblioref">2000</a>)</span>)</p>
<p>Here <span class="math inline">\(\pi_i\)</span> assigns a probability of the ith outcome taking a value of 1, meaning the probability of the ith outcome taking a value of 0 is <span class="math inline">\(1 - \pi_i\)</span>. For multinomial logistic regression this generalises to:</p>
<p><span class="math display">\[
Y_i ∼ Multinomial(y_i, \pi_{ij} ) , \pi_{ij} = \frac{exp⁡(x_i \beta_j )}{\sum_{k=1}^{J}exp⁡(x_i \beta_k ) }
\]</span></p>
<p>(See <span class="citation" data-cites="multinom2017"><span>“Multinomial Logistic Regression Model Specification”</span> (<a href="#ref-multinom2017" role="doc-biblioref">2017</a>)</span>)</p>
<p>Where in the above there are <span class="math inline">\(J\)</span> mutually exclusive outcomes that Y_i can take, where <span class="math inline">\(J = K-1\)</span>, and <span class="math inline">\(K\)</span> is the total number of mutually exclusive and exhaustive states that can be possible outcomes for observation <span class="math inline">\(i\)</span>. The difference between <span class="math inline">\(J\)</span> and <span class="math inline">\(K\)</span> is due to the need for a reference category, analogous to the 0 outcome in standard logistic regression. Just as the predicted probability of observation i taking an outcome 0 in standard logistic regression is <span class="math inline">\(1- \pi_i\)</span> , so the predicted probability of observation i taking the reference category outcome in multinomial logistic regression is <span class="math inline">\(1- \sum_{k=1}^{J} \pi_{ik}\)</span>.</p>
</section>
<section id="selecting-between-model-specifications" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="selecting-between-model-specifications"><span class="header-section-number">8.2.2</span> Selecting between model specifications</h3>
<p>Different model specifications, involving different predictors <span class="math inline">\(X\)</span>, are compared using Akaike’s Information Criterion (AIC) and the Bayesian Information Criterion (BIC), even where models are not nested <span class="citation" data-cites="akaike1974 schwarz1978">(<a href="#ref-akaike1974" role="doc-biblioref">Akaike 1974</a>; <a href="#ref-schwarz1978" role="doc-biblioref">Schwarz 1978</a>)</span>. In either case, lower scores are generally considered to indicate a better trade-off between model complexity and model fit, and BIC tends to penalise model complexity more severely than AIC, leading to more parsimonious models being selected. Where AIC and BIC ‘prefer’ different model specifications, researcher judgement was used to determine which model specification to adopt, for both the ‘foundational’ and ‘extended’ model specifications.</p>
</section>
<section id="simulation-to-quantify-the-effects-of-specific-factors" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="simulation-to-quantify-the-effects-of-specific-factors"><span class="header-section-number">8.2.3</span> Simulation to quantify the effects of specific factors</h3>
<p>With a model specification selected as described above, after being calibrated on the available data, the model can then be used to estimate the influence of one or more specific factors on both individual level conditional probabilities to transition to different mutually exclusive states, and the composition of a population beginning in heterogeneous states ending up each of the mutually exclusive states. The latter process, population level modelling, depends on the former process: the modelling of conditional transition for an individual with a known state at time T to each of the mutually exclusive states at time T+1. This section will therefore describe how the modelling can be used to simulate the effects of a given factor of interest on individual-level transitions, before then describing how the approach can be used to estimate the effects of a given factor for a population. To start with, let us say that model <span class="math inline">\(M(.)\)</span> has been calibrated on observed data <span class="math inline">\(D ≡ \{y,X\}\)</span>, where <span class="math inline">\(y\)</span> is the observed response and <span class="math inline">\(X\)</span> is the observed predictor matrix. Given any valid set of predictor variables for an individual <span class="math inline">\(X_i\)</span> the model will generate expected probabilities <span class="math inline">\(E(Y_i )= P\)</span> where <span class="math inline">\(P ≡ {p_1,p_2,…,p_J }\)</span>, <span class="math inline">\(p_0= 1- \sum_{j=1}^{J}p_j\)</span> and <span class="math inline">\(\sum_{j=1}^J p_j &lt;1\)</span>. (i.e.&nbsp;the model will generate mutually exclusive and exhaustive expected probabilities for each of the <span class="math inline">\(K\)</span> mutually exclusive states where, as before, <span class="math inline">\(K=J+1\)</span>.)</p>
<p>Given the above, the model will generate mutually exclusive and exhaustive predicted probabilities of being in each state at time <span class="math inline">\(T+1\)</span>, <span class="math inline">\(P^*\)</span>, given a <em>hypothetical</em> predictor set <span class="math inline">\(X_i^*\)</span>. We can further imagine splitting this hypothetical predictor set into components <span class="math inline">\(X_i^*= \{W_i,Y_i (T),Z\}\)</span>, where <span class="math inline">\(W_i\)</span> represents a range of modelled factors (such as age and sex) to control for, <span class="math inline">\(Y_i (T)\)</span> represents the economic (in)activity state at time <span class="math inline">\(T\)</span>, and <span class="math inline">\(Z\)</span> represents a factor (or set of factors) of interest.</p>
<p>We can now define two predictor sets: <span class="math inline">\(X_i^{Trt}= \{W_i,Y_i (T),Z= Z^{Trt} \}\)</span>, and <span class="math inline">\(X_i^{Ctr}= \{W_i,Y_i (T),Z= Z^{Ctr} \}\)</span>. Note that these differ only in terms of the contents of the factor or factors of interest <span class="math inline">\(Z\)</span>, with all other variables identical. To simplify, let us assume that <span class="math inline">\(Z=1\)</span> for <span class="math inline">\(X_i^{Trt}\)</span>, and <span class="math inline">\(Z=0\)</span> for <span class="math inline">\(X_i^{Ctr}\)</span>, i.e.&nbsp;that <span class="math inline">\(Z\)</span> is a binary indicator which marks the individual as either exposed or not exposed to the specific factor of interest. We can then define a model-derived treatment effect relating to this factor as <span class="math inline">\({TE}_i=E(Y_i^{Trt})-E(Y_i^{Ctr})\)</span> where <span class="math inline">\(Y_i^*\)</span> is the model prediction given <span class="math inline">\(X_i^*\)</span> as input. Along with the conditions stated above - that <span class="math inline">\(p_0 = 1 - \sum_{j=1}^J p_j\)</span> and that <span class="math inline">\(J\)</span> is one less <span class="math inline">\(K\)</span>, we have two vectors of predicted probabilities of length K: <span class="math inline">\(\{p_0^{Trt},p_1^{Trt},p_2^{Trt} ,…,p_J^{Trt} \}\)</span> and <span class="math inline">\(\{p_0^{Ctr},p_1^{Ctr},p_2^{Ctr} ,…,p_J^{Ctr} \}\)</span>. Our simulated treatment effect for individual <span class="math inline">\(i\)</span> will therefore be a vector of length <span class="math inline">\(K\)</span>: <span class="math inline">\(\{p_0^{Trt}- p_0^{Ctr},p_1^{Trt}- p_1^{Ctr},p_2^{Trt}- p_2^{Ctr} ,…,p_J^{Trt}- p_J^{Ctr} \}\)</span>, where the value of each element will be above 0 if the estimated probability of being in the state indicated by the position element is greater in the treatment condition (where <span class="math inline">\(Z=1\)</span>) than in the control condition (where <span class="math inline">\(Z=0\)</span>); and below 0 if the probability is estimated to be higher in the control than the treatment condition.</p>
</section>
<section id="moving-from-individual-level-to-population-level-estimates" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="moving-from-individual-level-to-population-level-estimates"><span class="header-section-number">8.2.4</span> Moving from individual level to population level estimates</h3>
<p>We can extend the intuition of the above to estimating the effect of a given factor of interest <span class="math inline">\(Z\)</span> for a population rather than an individual as follows. If we define <span class="math inline">\(X^{Ref}\)</span> as a matrix of dimensions <span class="math inline">\(m\)</span> by <span class="math inline">\(p\)</span>, where <span class="math inline">\(m\)</span> is the number of rows (number of hypothetical individuals) and <span class="math inline">\(p\)</span> the number of columns (number of predictors) then we can say that the contents for each row of <span class="math inline">\(X^{Ref}\)</span>, <span class="math inline">\(X_i^{Ref}\)</span>, are <span class="math inline">\(\{W_i,Y_i (T),Z=Z_i \}\)</span>. Again, in the simple case of a binary indicator for <span class="math inline">\(Z\)</span>, <span class="math inline">\(Z_i\)</span> could take on a value of either 0 or 1. We can now define a counterfactual matrix, <span class="math inline">\(X^{Alt}\)</span>, whose dimensions and values are identical to that of <span class="math inline">\(X^{Ref}\)</span>, except that all values of <span class="math inline">\(Z\)</span> are now set to 0, i.e.&nbsp;<span class="math inline">\(X_i^{Alt}= \{W_i,Y_i (T),Z=0\}\)</span> for all i. If we now slightly redefine <span class="math inline">\(P\)</span> as an m-by-K (rather than m-by-J) dimension matrix of conditional expected probabilities including the probabilities of <span class="math inline">\(p_0\)</span> (i.e.&nbsp;the reference category state) we can now define the matrix of expected probabilities given <span class="math inline">\(X^{Ref}\)</span> as <span class="math inline">\(P^{Ref}\)</span> and given <span class="math inline">\(X^{Alt}\)</span> as <span class="math inline">\(P^{Alt}\)</span>. With both <span class="math inline">\(P^{Ref}\)</span> and <span class="math inline">\(P^{Alt}\)</span> we can now produce modelled estimates of the number of individuals projected to be in each of the <span class="math inline">\(K\)</span> mutually exclusive states through column-wise summation of each <span class="math inline">\(P\)</span> matrix. This will produce two vectors, <span class="math inline">\(S^{Ref}\)</span> and <span class="math inline">\(S^{Alt}\)</span>, both of length <span class="math inline">\(K\)</span>, whose elements are <span class="math inline">\(\{s_0^{Ref},s_1^{Ref},…,s_J^{Ref} \}\)</span> and <span class="math inline">\(\{s_0^{Alt},s_1^{Alt},…,s_J^{Alt} \}\)</span> respectively. For both <span class="math inline">\(S^{Ref}\)</span> and <span class="math inline">\(S^{Alt}\)</span>, the sum of all elements will be <span class="math inline">\(m\)</span>, the number of rows in <span class="math inline">\(X\)</span>, because for any row of <span class="math inline">\(X\)</span>, <span class="math inline">\(X_i\)</span>, the sum of all row-wise probabilities must equal 1.</p>
</section>
<section id="using-the-approach-to-estimate-pafs-and-safs" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="using-the-approach-to-estimate-pafs-and-safs"><span class="header-section-number">8.2.5</span> Using the approach to estimate PAFs and SAFs</h3>
<p>What the above means is that the contents of <span class="math inline">\(S^{Ref}\)</span> and <span class="math inline">\(S^{Alt}\)</span> give the predicted pool sizes for a population of individuals in each mutually exclusive state under conditions that differ only in terms of the presence, absence or value of the particular factor of interest <span class="math inline">\(Z\)</span>. This means that for a particular state <span class="math inline">\(j\)</span> then <span class="math inline">\(s_j^{Alt} - s_j^{Ref}\)</span> will give <em>the additional number of persons in state j that can be attributed to Z</em>, and <span class="math inline">\(\frac{s_j^{Alt}- s_j^{Ref}}{s_j^{Ref}}\)</span> <em>the relative difference in state</em> <span class="math inline">\(j\)</span> pool size that can be attributed to <span class="math inline">\(Z\)</span>. This latter quantity can be of particular interest as, when <span class="math inline">\(Z\)</span> comprises a single factor, then it can be interpreted as a population-attributable fraction (PAF), i.e.&nbsp;the proportion of the state pool size that can be ‘explained by’ the factor of interest. Where <span class="math inline">\(Z\)</span> comprises more than one factor, then the selective ‘switching on’ and ‘switching off’ of factors within the model can be used to estimate the related sequential attributable fractions (SAFs) of the marginal contributions of any specific faction given the presence or absence of other factors of interest.</p>
</section>
</section>
<section id="including-continuous-variables-in-the-model" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="including-continuous-variables-in-the-model"><span class="header-section-number">8.3</span> Including continuous variables in the model</h2>
<p>The descriptions above have considered the case where <span class="math inline">\(Z\)</span> takes on a binary value, <code>0</code> or <code>1</code>. Where <span class="math inline">\(Z\)</span> takes on a continuous value, the values of <span class="math inline">\(Z\)</span> are first normalized and standardized to have a mean of 0 and standard deviation of 1. In the control/reference population the observed values (after standardisation and normalisation) are used; for the alternative population a value of 1 is either added or subtracted to the observed values, depending on whether the factor of interest is something to which population exposure should ideally be maximized (so added) or minimized (so subtracted). In either case, this is equivalent to an alternative/counterfactual scenario in which the exposure to the factor of interest has been shifted by one standardised unit in the ‘good’ direction.</p>
</section>
<section id="appendix-c-illustrative-individual-level-vignettes" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="appendix-c-illustrative-individual-level-vignettes"><span class="header-section-number">8.4</span> Appendix C: Illustrative individual level vignettes</h2>
<section id="predictive-accuracy-2" class="level4" data-number="8.4.0.1">
<h4 data-number="8.4.0.1" class="anchored" data-anchor-id="predictive-accuracy-2"><span class="header-section-number">8.4.0.1</span> Predictive accuracy</h4>
<p>The discrete health extended model specification has an average predicted model accuracy score of <code>0.7858</code>, as opposed to <code>0.7847</code> for the foundational model, when both are assessed using the data used to fit them, showing a marginal improvement in fit associated with including this variable.</p>
</section>
<section id="vignette-examples-predicted-effects-of-health-1" class="level4" data-number="8.4.0.2">
<h4 data-number="8.4.0.2" class="anchored" data-anchor-id="vignette-examples-predicted-effects-of-health-1"><span class="header-section-number">8.4.0.2</span> Vignette examples: Predicted effects of health</h4>
<p>To illustrate the substantive predicted effects of health the following vignettes are presented both where an LLTI is present (<code>lt_condition = TRUE</code>) or absent (<code>lt_condition=FALSE</code>)</p>
<ul>
<li>Male, aged 25 or 50. Either Employed, Unemployed, or Economically Inactive, Long-term sick</li>
<li>Female, aged 25 or 50. Either Employed, Unemployed, or Economically Inactive, Long-term sick</li>
</ul>
<p>These vignettes are presented in <a href="#tbl-vignettes-health-discrete">Table&nbsp;12</a></p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-vignettes-health-discrete" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;12: Illustrative vignettes of predictions for next economic status given sex, age, a long term health condition, and either employed, unemployed or inactivity due to long-term sickness as current activity states</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">sex</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">this_status</th>
<th style="text-align: left;">lt_condition</th>
<th style="text-align: right;">Employed</th>
<th style="text-align: right;">Inactive care</th>
<th style="text-align: right;">Inactive long term sick</th>
<th style="text-align: right;">Inactive other</th>
<th style="text-align: right;">Inactive retired</th>
<th style="text-align: right;">Inactive student</th>
<th style="text-align: right;">Unemployed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.953</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.930</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.040</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.046</td>
<td style="text-align: right;">0.524</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.559</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: right;">0.432</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.192</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.945</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.440</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.453</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.212</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.451</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.163</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.422</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.296</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.831</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.934</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.020</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.910</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.310</td>
<td style="text-align: right;">0.217</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.049</td>
<td style="text-align: right;">0.392</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.182</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">0.430</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">0.245</td>
<td style="text-align: right;">0.238</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">0.276</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">0.688</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.137</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.932</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.340</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">0.162</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.347</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">0.191</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.061</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.194</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">0.807</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.073</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The predicted absolute effects of health for each of these vignettes are as shown in <a href="#tbl-hlth-disc-diffs">Table&nbsp;13</a>:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-hlth-disc-diffs" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;13: Differences in proportions in different economic activity states as a result of having or not having a LLTI</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">sex</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">this_status</th>
<th style="text-align: right;">Employed</th>
<th style="text-align: right;">Inactive care</th>
<th style="text-align: right;">Inactive long term sick</th>
<th style="text-align: right;">Inactive other</th>
<th style="text-align: right;">Inactive retired</th>
<th style="text-align: right;">Inactive student</th>
<th style="text-align: right;">Unemployed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">-0.025</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">-0.113</td>
<td style="text-align: right;">-0.152</td>
<td style="text-align: right;">0.450</td>
<td style="text-align: right;">-0.007</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">-0.039</td>
<td style="text-align: right;">-0.138</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">-0.094</td>
<td style="text-align: right;">-0.034</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">-0.122</td>
<td style="text-align: right;">-0.136</td>
<td style="text-align: right;">0.437</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">-0.042</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">-0.121</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">-0.130</td>
<td style="text-align: right;">-0.046</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">-0.124</td>
<td style="text-align: right;">-0.026</td>
<td style="text-align: right;">0.441</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">-0.039</td>
<td style="text-align: right;">-0.240</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">-0.119</td>
<td style="text-align: right;">-0.005</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.010</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Employed</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Inactive long term sick</td>
<td style="text-align: right;">-0.128</td>
<td style="text-align: right;">-0.022</td>
<td style="text-align: right;">0.409</td>
<td style="text-align: right;">-0.014</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">-0.196</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">50</td>
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">-0.161</td>
<td style="text-align: right;">-0.006</td>
<td style="text-align: right;">0.175</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">-0.002</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The effects of <code>lt_condition</code> on the absolute changes in probability of being in each of these states therefore differs quite a lot by individual characteristics. For example, the effect of a long term condition on the probability of being predicted to be Inactive long-term sick ranges from around 45% for some vignette scenarios to less than 1% for others.</p>
</section>
</section>
<section id="appendix-d-out-of-sample-predictive-scores-for-different-foundational-model-specifications" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="appendix-d-out-of-sample-predictive-scores-for-different-foundational-model-specifications"><span class="header-section-number">8.5</span> Appendix D: Out-of-sample predictive scores for different foundational model specifications</h2>
<p>For each of the eight foundational model specifications two types of test were performed to try to determine the best specification to use. Firstly, AIC and BIC were calculated and compared. These are measures of penalised model fit, where lower scores are by convention taken to indicate better fit. Comparison of AIC and BIC indicated that models including the interaction term were to be prefered to those without an interaction term, but the relative ranking of AIC and BIC scores for the four models with interaction terms were reversed, with AIC ‘preferring’ the simpler models and BIC the most complicated.</p>
<p>In order to select between the four model specifications with interaction terms, but differing in terms of the <code>df</code> parameter in <code>bs()</code> function, the mean accuracy scores for out-of-sample fit were calculated. This involves fitting the model as per the specification of interest on a randomly selected 80% of the dataset, then holding back 20% of the dataset as a test set. For each observation in the test set the model produced a vector of probabilities of being in each of the seven mutually exclusive and exhaustive states summing to one. The accuracy score for a single observation was determined by identifying the probability predicted from the model for the correct categorical assignment (i.e.&nbsp;economic state at wave + 1, i.e.&nbsp;the observed value for <code>next_status</code> using the terms in the formula expression above). For example, if for an observation the observed <code>next_status</code> was ‘Employed’, and for this observation the model predicted <code>Employed</code> with a probability of <code>0.90</code>, then the model’s prediction was given an accuracy score of <code>0.90</code>. The accuracy metric of interest is the mean accuracy score across all observations in the test set.</p>
<p>For each of the four models, the exercise - fitting the model on the training set and calculating mean accuracy on the test test - was repeated fifty times. The mean, median, and lower upper quartiles of the ranges of the these mean accuracy scores were calculated and compared.</p>
<p>Using this exercise, all four model specifications were estimated to have very similar mean accuracy scores, predicting the correct <code>next_state</code> on average between 78.4% and 78.5% of the time. The only differences in the out-of-sample predictive accuracies between the models were to additional numbers of decimal places. By a very small margin, the model whose specification is described above, with <code>df=5</code> set in the <code>bs()</code> function for the age spline, outperformed models where either <code>df=3</code>, <code>df=4</code> or <code>df=6</code> was used instead. This is why this particular specification was used as the foundational model specification, even though the reasons for preferring this specification to similar alternatives are not compelling.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-aic-bic-fnd-health-only" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;14: AIC and BIC scores and rankings for eight candidate foundational models using only data containing health variables of interest</caption>
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">aic_rank</th>
<th style="text-align: right;">bic_rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fnd_00</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">249831.9</td>
<td style="text-align: right;">250525.3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_01</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">249787.9</td>
<td style="text-align: right;">250544.3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_02</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">249771.3</td>
<td style="text-align: right;">250590.7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_03</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">249754.9</td>
<td style="text-align: right;">250637.3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_04</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">249302.0</td>
<td style="text-align: right;">250373.5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_05</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">249257.5</td>
<td style="text-align: right;">250392.1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fnd_06</td>
<td style="text-align: right;">114</td>
<td style="text-align: right;">249241.1</td>
<td style="text-align: right;">250438.7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">fnd_07</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">249224.5</td>
<td style="text-align: right;">250485.1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#tbl-aic-bic-fnd-health-only">Table&nbsp;14</a> shows that this does not resolve the choice of which model to use as the foundational model.</p>
<p>So a different approach will be used. For each interaction model, from <code>fnd_04</code> through to <code>fnd_07</code>, we will do the following:</p>
<ul>
<li>Sample 80% of the data as the training set</li>
<li>Hold back 20% of the data as the test set</li>
<li>For the test set calculate the proportion of classifications that are correct in the test set.</li>
</ul>
<p>n.b.&nbsp;we will use the response = <code>probs</code> argument to reduce the amount of stochastic variation in the experiment. This means that, for example, if the model predicts the correct answer with a 90% probability then it is assigned a score of 0.90, and so on.</p>
<p>The above process will be repeated 50 times (as the models take some time to run)</p>
<div id="tbl-oos-fnd" class="cell tbl-parent quarto-layout-panel anchored" data-tbl-cap="Out of sample predictive accuracy of four foundational model specifications, each based on 50 replicates. All accuracies scores are out of 100,000. lql and uql refer to lower quartile and upper quartile respectively.">

</div>
<p>This table [X] suggests that all model specifications have very similar properties in terms of out-of-sample predictive accuracy. On average all models correctly predict the next state around 78% of the time. Differences in predictive accuracy are largely detectable only after the third decimal place in the accuracy scores.</p>
<p>Overally, it appears model <code>fnd_06</code> has slightly higher accuracy than the other specifications. This is the specification originally selected as the baseline specification.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This assessment of whether additional lagged terms on y should be included is conceptually similar to the selection of the number of autoregressive terms <span class="math inline">\(p\)</span> to use in an <span class="math inline">\(AR(p)\)</span> model specification <span class="citation" data-cites="hyndman2021">(<a href="#ref-hyndman2021" role="doc-biblioref">Hyndman and Athanasopoulos 2021</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>