<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jon Minton">
<meta name="dcterms.date" content="2024-03-23">

<title>Health Economics Simulation Experiment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="health-econ-sim_files/libs/clipboard/clipboard.min.js"></script>
<script src="health-econ-sim_files/libs/quarto-html/quarto.js"></script>
<script src="health-econ-sim_files/libs/quarto-html/popper.min.js"></script>
<script src="health-econ-sim_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="health-econ-sim_files/libs/quarto-html/anchor.min.js"></script>
<link href="health-econ-sim_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="health-econ-sim_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="health-econ-sim_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="health-econ-sim_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="health-econ-sim_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="health-econ-sim.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Health Economics Simulation Experiment</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jon Minton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="other-pertinent-linksmaterials" class="level2">
<h2 class="anchored" data-anchor-id="other-pertinent-linksmaterials">Other pertinent links/materials</h2>
<ul>
<li><p><a href="https://rpubs.com/JonMinton/edinbr-econinact">Presentation on EI model</a></p>
<ul>
<li><a href="https://rpubs.com/JonMinton/effect-wages-staying-employed">Example of age-wage relationships</a></li>
</ul></li>
<li><p><a href="https://jonminton.github.io/jon-blog/glms.html">Technical Blog on statistical inference and simulation</a></p>
<ul>
<li><p><a href="https://jonminton.github.io/jon-blog/posts/glms/lms-are-glms-part-12/">Representing variation and uncertainty using Frequentist approaches</a></p></li>
<li><p><a href="https://jonminton.github.io/jon-blog/posts/glms/lms-are-glms-part-13/">Representing variation and uncertainty using Bayesian approaches</a></p></li>
</ul></li>
</ul>
</section>
<section id="purpose" class="level1">
<h1>Purpose</h1>
<p>This document will show a fairly minimal adaptation of an existing model to demonstrate how it could be used as part of a health economic model.</p>
<p>The model is in effect an <em>individual level</em> markov model of economic activity status, including seven distinct states of economic activity and inactivity.</p>
<p>The data used are all pre-COVID waves of the UK Household Longitudinal Study (UKHLS), where information about participant characteristics in the current and next wave are available.</p>
<p>The model uses multinomial logistic regression, with the economic activity status at wave T+1 as the response, and including existing economic activity status at wave T as a predictor. Age and sex are also included as predictors, with a spline term used for age, and an interaction between sex and economic activity status at wave T included. This model specification was determined by comparing AIC and BIC for a range of model specifications.</p>
<p>The foundational model, which includes state at T, age and sex as predictors, as predictors, is adapted to also include clinical depression as a predictor.</p>
<p>A hypothetical generic intervention, costing £400 a year, which reduces the probability of ‘limiting long term illness’ by 20%, is then modelled. The number of people in each economic activity state is then projected given this scenario. Each economic state is associated with a different utility score and net societal cost excluding the cost to the NHS.</p>
<section id="packages-used" class="level2">
<h2 class="anchored" data-anchor-id="packages-used">Packages used</h2>
<ul>
<li>Bespoke functions (loaded as package)</li>
<li>tidyverse</li>
<li>nnet (for multinomial logit function)</li>
</ul>
</section>
</section>
<section id="data-preparation" class="level1">
<h1>Data preparation</h1>
<p>We can start with the binary <code>health</code> variable as described in <a href="https://www.understandingsociety.ac.uk/documentation/mainstage/variables/health/">this page</a>. This is effectively an indicator for whether people have a limiting long-term condition or not.</p>
</section>
<section id="preparation" class="level1">
<h1>Preparation</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">load_all</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">'R'</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># library(haven)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># library(here)</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>varnames <span class="ot">&lt;-</span>  <span class="fu">c</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"jbstat"</span>, <span class="st">"dvage"</span>, <span class="st">"sex"</span>, <span class="st">"health"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>vartypes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"labels"</span>, <span class="st">"values"</span>, <span class="st">"labels"</span>, <span class="st">"labels"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>df_ind <span class="ot">&lt;-</span> <span class="fu">get_ind_level_vars_for_selected_waves</span>(<span class="at">varnames =</span> varnames, <span class="at">vartypes =</span> vartypes, <span class="at">waves =</span> letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>])</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the data </span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>df_ind_health_standardised <span class="ot">&lt;-</span> </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  df_ind <span class="sc">|&gt;</span> </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># dvage uses negative values to indicate missing. The code below explicitly turns them all to missing values</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(dvage, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="cn">NA</span>, x))) <span class="sc">|&gt;</span> </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># This renames dvage to age</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">age =</span> dvage) <span class="sc">|&gt;</span> </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">between</span>(age, <span class="dv">16</span>, <span class="dv">64</span>))  <span class="sc">|&gt;</span> </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">lt_condition =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        health <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"no"</span>) <span class="sc">~</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        health <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"yes"</span>) <span class="sc">~</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_integer_</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">|&gt;</span> <span class="fu">as.logical</span>()</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="foundational-model" class="level2">
<h2 class="anchored" data-anchor-id="foundational-model">Foundational model</h2>
<p>The foundational model is specified as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mod_00 <span class="ot">&lt;-</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  nnet<span class="sc">::</span><span class="fu">multinom</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    next_status <span class="sc">~</span> this_status <span class="sc">*</span> sex <span class="sc">+</span> splines<span class="sc">::</span><span class="fu">bs</span>(age, <span class="dv">5</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_ind_health_standardised <span class="sc">|&gt;</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(lt_condition)),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">maxit =</span> <span class="dv">200</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  238 (198 variable)
initial  value 593459.785440 
iter  10 value 217065.229935
iter  20 value 181835.205003
iter  30 value 176173.701928
iter  40 value 169054.073365
iter  50 value 162622.177139
iter  60 value 158455.088600
iter  70 value 154995.077286
iter  80 value 153202.192527
iter  90 value 150817.463737
iter 100 value 147188.232683
iter 110 value 144869.729481
iter 120 value 144353.815392
iter 130 value 144208.112001
iter 140 value 144201.656766
iter 150 value 144200.269008
iter 160 value 144200.150263
final  value 144200.130290 
converged</code></pre>
</div>
</div>
<p>Within the above the formula is <code>next_status ~ this_status * sex + splines::bs(age, 5)</code>. The predicted variables are to the left of the <code>~</code>. The predictor variables are to the right of the <code>~</code>.</p>
<p>If the model specification were <code>next_status ~ this_status</code>, then the model would effectively be an individual markov model, with probability of moving to or staying in each state at time T+1 dependent on the state at time T.</p>
<p>The inclusion of <code>this_status * sex</code> is shorthand for <code>this_status + sex + this_status:sex</code>, i.e.&nbsp;both independent effects, and a status:sex interaction. This was found to be important mainly because male and female patterns of engagement with the <code>economically inactive - looking after home and family</code> states are quite different.</p>
<p>The <code>splines::bs(age, 5)</code> term is a spline term for age, with 5 degrees of freedom. This was found to be important because the relationship between age and economic activity status is not linear, and to be dissimilar between states and transitions. The spline term appears to be flexible enough to capture this. Both fewer and more degrees of freedom were found to have lower AICs and BICs on average.</p>
<p>We can see what the model predicts given different predictors as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">this_status =</span> <span class="fu">unique</span>(df_ind_health_standardised<span class="sc">$</span>this_status),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">c</span>(<span class="st">'female'</span>, <span class="st">'male'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>predictions_m00 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_00, <span class="at">newdata =</span> predictors, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m00 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(predictors, predictions_m00) <span class="sc">|&gt;</span> </span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(this_status, age, sex), <span class="at">names_to =</span> <span class="st">"next_status"</span>, <span class="at">values_to =</span> <span class="st">"probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m00 <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(next_status, this_status, <span class="at">fill =</span> probability, <span class="at">label =</span> <span class="fu">round</span>(probability, <span class="dv">2</span>))) <span class="sc">+</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(age <span class="sc">~</span> sex) <span class="sc">+</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">color =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Estimated age-sex specific transition probabilities"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Status at current period"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Status at next period"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"For males and female, at ages 30, 40, 50 and 60"</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="health-econ-sim_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="768"></p>
</div>
</div>
</section>
<section id="health-model-extension" class="level2">
<h2 class="anchored" data-anchor-id="health-model-extension">Health model extension</h2>
<p>We next extend the model to include the health variable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mod_01 <span class="ot">&lt;-</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  nnet<span class="sc">::</span><span class="fu">multinom</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    next_status <span class="sc">~</span> this_status <span class="sc">*</span> sex <span class="sc">+</span> splines<span class="sc">::</span><span class="fu">bs</span>(age, <span class="dv">5</span>) <span class="sc">+</span> lt_condition,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_ind_health_standardised,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">maxit =</span> <span class="dv">200</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  245 (204 variable)
initial  value 593459.785440 
iter  10 value 191760.039731
iter  20 value 184082.812596
iter  30 value 178733.279863
iter  40 value 158204.780390
iter  50 value 152963.660689
iter  60 value 150905.271984
iter  70 value 145439.304192
iter  80 value 143925.206548
iter  90 value 143354.046183
iter 100 value 142852.336483
iter 110 value 142582.530287
iter 120 value 142464.747406
iter 130 value 142419.416446
iter 140 value 142363.195144
iter 150 value 142360.107659
iter 160 value 142359.303880
iter 170 value 142359.246225
final  value 142359.228993 
converged</code></pre>
</div>
</div>
<p>We can check that the model fit has improved by comparing AIC and BIC:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(mod_00, mod_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        df      AIC
mod_00 126 288652.3
mod_01 132 284982.5</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(mod_00, mod_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        df      BIC
mod_00 126 289991.4
mod_01 132 286385.4</code></pre>
</div>
</div>
<p>In both cases the penalised values are lower, indicating an improvement in model fit.</p>
<p>We can now construct the same kinds of transition matrices, but including both with and without a long term condition as another covariate in the predictor matrix:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">this_status =</span> <span class="fu">unique</span>(df_ind_health_standardised<span class="sc">$</span>this_status),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">c</span>(<span class="st">'female'</span>, <span class="st">'male'</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lt_condition =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>predictions_m01 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_01, <span class="at">newdata =</span> predictors, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m01 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(predictors, predictions_m01) <span class="sc">|&gt;</span> </span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(this_status, age, sex, lt_condition), <span class="at">names_to =</span> <span class="st">"next_status"</span>, <span class="at">values_to =</span> <span class="st">"probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For everyone who does not have a long term condition, the transition matrices look as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m01 <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(next_status, this_status, <span class="at">fill =</span> probability, <span class="at">label =</span> <span class="fu">round</span>(probability, <span class="dv">2</span>))) <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(age <span class="sc">~</span> sex) <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">color =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"No LT condition: Estimated age-sex specific transition probabilities"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Status at current period"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Status at next period"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"For males and female, at ages 30, 40, 50, 60"</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="health-econ-sim_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>Now the same if everyone else had a long term condition:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m01 <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(next_status, this_status, <span class="at">fill =</span> probability, <span class="at">label =</span> <span class="fu">round</span>(probability, <span class="dv">2</span>))) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(age <span class="sc">~</span> sex) <span class="sc">+</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">color =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"LT condition: Estimated age-sex specific transition probabilities"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Status at current period"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Status at next period"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"For males and female, at ages 30, 40, 50, 60"</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="health-econ-sim_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>We can see the effects that a long term condition has on transition probabilities as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>predictors_predictions_m01 <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> lt_condition, <span class="at">values_from =</span> probability) <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff_prop =</span> <span class="st">`</span><span class="at">TRUE</span><span class="st">`</span> <span class="sc">-</span> <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">TRUE</span><span class="st">`</span>, <span class="sc">-</span><span class="st">`</span><span class="at">FALSE</span><span class="st">`</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(next_status, this_status, <span class="at">fill =</span> diff_prop, <span class="at">label =</span> <span class="fu">round</span>(diff_prop, <span class="dv">2</span>))) <span class="sc">+</span> </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(age <span class="sc">~</span> sex) <span class="sc">+</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">color =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low =</span> <span class="st">"darkred"</span>, <span class="at">mid =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"darkblue"</span>, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="at">by =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Effect of long-term condition on transition probabilities"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Status at current period"</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Status at next period"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"For males and female, at ages 30, 40, 50, 60"</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="health-econ-sim_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<p>We can see the effect of the health condition increased the probability of someone remaining inactive LT sick by about 0.45.</p>
</section>
<section id="adding-a-health-economic-component" class="level2">
<h2 class="anchored" data-anchor-id="adding-a-health-economic-component">Adding a health economic component</h2>
<p>Let’s say we’re considering two perspectives:</p>
<ul>
<li>NHS</li>
<li>Societal</li>
</ul>
<p>Let’s say we are also considering two population groups:</p>
<ul>
<li>30 year old females, initially all Employed</li>
<li>60 year old males, initially all Economically inactive - long term sick</li>
</ul>
<p>Initially these populations all have a LT condition.</p>
<p>Let’s also imagine we have an intervention that costs £400 a year, and reduces the probability of having a LT condition by 20%.</p>
<p>Let’s say also our utility tariffs are the same by state:</p>
<ul>
<li>Employed: 0.80</li>
<li>Unemployed: 0.55</li>
<li>Economically inactive - full time carer: 0.60</li>
<li>Economically inactive - retired: 0.60</li>
<li>Economically inactive - sick: 0.30</li>
<li>Economically inactive - other: 0.35</li>
<li>Economically inactive - student: 0.75</li>
</ul>
<section id="nhs-perspective" class="level3">
<h3 class="anchored" data-anchor-id="nhs-perspective">NHS perspective</h3>
<p>Let’s specify the utility tarrifs:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>utility_tariffs <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>state, <span class="sc">~</span>utility,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Employed"</span>, <span class="fl">0.80</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Unemployed"</span>, <span class="fl">0.55</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive care"</span>, <span class="fl">0.60</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive retired"</span>, <span class="fl">0.60</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive long term sick"</span>, <span class="fl">0.30</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive other"</span>, <span class="fl">0.35</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive student"</span>,  <span class="fl">0.75</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s now create predicted probabilities for the with and without LT condition groups, and then attach the utilities:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>first_population_scenario <span class="ot">&lt;-</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="st">"female"</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="dv">30</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">this_status =</span> <span class="st">"Employed"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lt_condition =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>predictions_s01 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_01, <span class="at">newdata =</span> first_population_scenario, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s01 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(first_population_scenario, predictions_s01) <span class="sc">|&gt;</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(this_status, age, sex, lt_condition), <span class="at">names_to =</span> <span class="st">"next_status"</span>, <span class="at">values_to =</span> <span class="st">"probability"</span>) </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Now attach utilities to next_status</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>population_group_01_pred_utility <span class="ot">&lt;-</span> </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s01 <span class="sc">|&gt;</span> </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(utility_tariffs, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"next_status"</span> <span class="ot">=</span> <span class="st">"state"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">component =</span> utility <span class="sc">*</span> probability) <span class="sc">|&gt;</span> </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lt_condition) <span class="sc">|&gt;</span> </span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_utility =</span> <span class="fu">sum</span>(component)) </span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>population_group_01_pred_utility</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  lt_condition total_utility
  &lt;lgl&gt;                &lt;dbl&gt;
1 FALSE                0.790
2 TRUE                 0.782</code></pre>
</div>
</div>
<p>So, the total utility for this type of person is, on average, 0.782 with a LT condition, and 0.790 without.</p>
<p>If our intervention costs £400 a year, and reduces the probability of having a LT condition by 20% then our improvement in utility is:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>util_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>util_no_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>utility_baseline_s01 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> util_lt_s01 </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>utility_counter_s01 <span class="ot">=</span> <span class="fl">0.8</span> <span class="sc">*</span> util_lt_s01 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> util_no_lt_s01 </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>change_in_utility_s01 <span class="ot">&lt;-</span> utility_counter_s01 <span class="sc">-</span> utility_baseline_s01</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>change_in_utility_s01</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001510271</code></pre>
</div>
</div>
<p>Our cost per change in utility is therefore:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s01 <span class="ot">&lt;-</span> <span class="dv">400</span> <span class="sc">/</span> change_in_utility_s01</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s01</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 264853.2</code></pre>
</div>
</div>
<p>Let’s now consider the second possible indication/population group:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>second_population_scenario <span class="ot">&lt;-</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_grid</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="st">"male"</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="dv">60</span>, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">this_status =</span> <span class="st">"Inactive long term sick"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lt_condition =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>predictions_s02 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_01, <span class="at">newdata =</span> second_population_scenario, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s02 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(second_population_scenario, predictions_s02) <span class="sc">|&gt;</span> </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(this_status, age, sex, lt_condition), <span class="at">names_to =</span> <span class="st">"next_status"</span>, <span class="at">values_to =</span> <span class="st">"probability"</span>) </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Now attach utilities to next_status</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>population_group_02_pred_utility <span class="ot">&lt;-</span> </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s02 <span class="sc">|&gt;</span> </span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(utility_tariffs, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"next_status"</span> <span class="ot">=</span> <span class="st">"state"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">component =</span> utility <span class="sc">*</span> probability) <span class="sc">|&gt;</span> </span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lt_condition) <span class="sc">|&gt;</span> </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_utility =</span> <span class="fu">sum</span>(component)) </span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>population_group_02_pred_utility</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  lt_condition total_utility
  &lt;lgl&gt;                &lt;dbl&gt;
1 FALSE                0.517
2 TRUE                 0.378</code></pre>
</div>
</div>
<p>As this group start from a state with a lower utility, the effect of removing LT sickness on aggregate utility is now larger.</p>
<p>Let’s calculate the expected change in utility as a result of the intervention for this group:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>util_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>util_no_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>utility_baseline_s02 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> util_lt_s02</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>utility_counter_s02 <span class="ot">=</span> <span class="fl">0.8</span> <span class="sc">*</span> util_lt_s02 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> util_no_lt_s02</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>change_in_utility_s02 <span class="ot">&lt;-</span> utility_counter_s02 <span class="sc">-</span> utility_baseline_s02</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>change_in_utility_s02</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02771122</code></pre>
</div>
</div>
<p>And now the cost per change in utility:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s02 <span class="ot">&lt;-</span> <span class="dv">400</span> <span class="sc">/</span> change_in_utility_s02</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s02</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14434.58</code></pre>
</div>
</div>
<p>For this (initially older, more economically inactive) population the cost per change in utility is much lower than for the younger employed population.</p>
</section>
</section>
<section id="societal-perspective" class="level2">
<h2 class="anchored" data-anchor-id="societal-perspective">Societal perspective</h2>
<p>We could also imagine that the time a person spends in each state is associated with a societal cost or value, which could also be considered in the analysis. We can do this by extending the tariffs dataframe to include a societal cost/benefit value too:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>utility_cost_tariffs <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>state, <span class="sc">~</span>utility, <span class="sc">~</span>cost,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Employed"</span>, <span class="fl">0.80</span>, <span class="sc">-</span><span class="dv">20000</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Unemployed"</span>, <span class="fl">0.55</span>, <span class="dv">15000</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive care"</span>, <span class="fl">0.60</span>, <span class="sc">-</span><span class="dv">7000</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive retired"</span>, <span class="fl">0.60</span>, <span class="dv">8000</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive long term sick"</span>, <span class="fl">0.30</span>, <span class="dv">28000</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive other"</span>, <span class="fl">0.35</span>, <span class="sc">-</span><span class="dv">4000</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Inactive student"</span>,  <span class="fl">0.75</span> , <span class="sc">-</span><span class="dv">9000</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s take the two hypothetical groups, but then also calculate aggregated societal costs as well as utilities:</p>
<p>First the 30 year old employed females</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now attach utilities AND costs to next_status</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>population_group_01_pred_cost_utility <span class="ot">&lt;-</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s01 <span class="sc">|&gt;</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(utility_cost_tariffs, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"next_status"</span> <span class="ot">=</span> <span class="st">"state"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">utility_component =</span> utility <span class="sc">*</span> probability) <span class="sc">|&gt;</span> </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cost_component =</span> cost <span class="sc">*</span> probability) <span class="sc">|&gt;</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lt_condition) <span class="sc">|&gt;</span> </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_utility =</span> <span class="fu">sum</span>(utility_component),</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_scost =</span> <span class="fu">sum</span>(cost_component)) </span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>population_group_01_pred_cost_utility</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  lt_condition total_utility total_scost
  &lt;lgl&gt;                &lt;dbl&gt;       &lt;dbl&gt;
1 FALSE                0.790     -18940.
2 TRUE                 0.782     -18152.</code></pre>
</div>
</div>
<p>When considering the societal perspective, we should include the aggregated (negative) scost as well as the direct treatment cost:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>util_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>util_no_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>scost_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_scost)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>scost_no_lt_s01 <span class="ot">&lt;-</span> population_group_01_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_scost)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>utility_baseline_s01 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> util_lt_s01</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>utility_counter_s01 <span class="ot">=</span> <span class="fl">0.8</span> <span class="sc">*</span> util_lt_s01 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> util_no_lt_s01</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>cost_baseline_s01 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> scost_lt_s01</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>cost_counter_s01 <span class="ot">=</span> <span class="dv">400</span> <span class="sc">+</span> <span class="fl">0.8</span> <span class="sc">*</span> scost_lt_s01 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> scost_no_lt_s01</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>diff_cost <span class="ot">&lt;-</span> cost_counter_s01 <span class="sc">-</span> cost_baseline_s01</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>diff_utility <span class="ot">&lt;-</span> utility_counter_s01 <span class="sc">-</span> utility_baseline_s01</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s01_societal <span class="ot">&lt;-</span> diff_cost <span class="sc">/</span> diff_utility</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s01_societal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 160411.4</code></pre>
</div>
</div>
<p>So, incorporating the societal perspective, the net cost per change in utility changes from £265,000/QALY to £160,000/QALY</p>
<p>Let’s now attempt the same for the second population group:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>population_group_02_pred_cost_utility <span class="ot">&lt;-</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>predictions_predictors_s02 <span class="sc">|&gt;</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(utility_cost_tariffs, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"next_status"</span> <span class="ot">=</span> <span class="st">"state"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">utility_component =</span> utility <span class="sc">*</span> probability) <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cost_component =</span> cost <span class="sc">*</span> probability) <span class="sc">|&gt;</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lt_condition) <span class="sc">|&gt;</span> </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_utility =</span> <span class="fu">sum</span>(utility_component),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_scost =</span> <span class="fu">sum</span>(cost_component)) </span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>population_group_02_pred_cost_utility</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  lt_condition total_utility total_scost
  &lt;lgl&gt;                &lt;dbl&gt;       &lt;dbl&gt;
1 FALSE                0.517      12383.
2 TRUE                 0.378      22506.</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>util_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>util_no_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_utility)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>scost_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_scost)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>scost_no_lt_s02 <span class="ot">&lt;-</span> population_group_02_pred_cost_utility <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lt_condition <span class="sc">==</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(total_scost)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>utility_baseline_s02 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> util_lt_s02</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>utility_counter_s02 <span class="ot">=</span> <span class="fl">0.8</span> <span class="sc">*</span> util_lt_s02 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> util_no_lt_s02</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>cost_baseline_s02 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">*</span> scost_lt_s02</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>cost_counter_s02 <span class="ot">=</span> <span class="dv">400</span> <span class="sc">+</span> <span class="fl">0.8</span> <span class="sc">*</span> scost_lt_s02 <span class="sc">+</span> <span class="fl">0.20</span> <span class="sc">*</span> scost_no_lt_s02</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>diff_cost <span class="ot">&lt;-</span> cost_counter_s02 <span class="sc">-</span> cost_baseline_s02</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>diff_utility <span class="ot">&lt;-</span> utility_counter_s02 <span class="sc">-</span> utility_baseline_s02</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s02_societal <span class="ot">&lt;-</span> diff_cost <span class="sc">/</span> diff_utility</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>cost_per_change_in_utility_s02_societal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -58624.37</code></pre>
</div>
</div>
<p>So, for this second indication, including the societal perspective leads to a negative cost per QALY gained from the intervention. i.e.&nbsp;the suggestion that the intervention is cost saving from a societal perspective.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In this script we have taken a model framework that is in effect an individual Markov model specification, based on real survey data, and used to to compare two scenarios for a hypothetical intervention on long-term sickness from two different payer perspectives.</p>
</section>
<section id="discussion-points" class="level2">
<h2 class="anchored" data-anchor-id="discussion-points">Discussion Points</h2>
<section id="uncertainty-and-variation" class="level3">
<h3 class="anchored" data-anchor-id="uncertainty-and-variation">Uncertainty and variation</h3>
<p>For Probabilistic Sensitivity Analysis (PSA) we should really include variation in predicted outputs from two sources:</p>
<ul>
<li>Stochastic variation: as we are modelling stochastic systems, each time the system is asked to make predictions there should be some variation in the predictions produced.</li>
<li>Parameter uncertainty: the model is based on a sample of the population, and so the parameter estimates are uncertain.</li>
</ul>
<p>The first of these types of output uncertainty can be modelled by changing the predict mode from ‘probs’ to ‘class’, and then running the model many times. The second can be addressed in at least two ways: 1) by bootstrapping the data and reestimating the model many times; 2) by making use of the optional Hessian output from the model to produce samples of joint distributions of model parameters, and passing these through the model link functions. An extension of the second approach would be to use a fully Bayesian modelling framework, where these parameter quantities form part of the posterior distribution.</p>
<p>There is also likely to be uncertainty in the estimation of the utilities and costs. Again these can be produced through simulation approaches, applying draws from appropriate distributions rather than fixed values, and repeating the exercise many times.</p>
</section>
<section id="integration-with-excel" class="level3">
<h3 class="anchored" data-anchor-id="integration-with-excel">Integration with Excel</h3>
<p>Some of the above can be done in Excel relatively easily. Other parts may require computation in something like R beforehand, then importing relevant results and estimates into Excel. Packages like <code>openxlsx</code> make it relatively straightforward to write R outputs to Excel sheets and cells, and format them, programatically.</p>
<p>For a more integrated approach, the Python language could take the place of the R package, as Python is increasingly taking the place of VBA within Excel.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>